### DISCUSSION TITLE
It is safe to use a Service name in routes in a helm chart?

### DISCUSSION THREAD

**Discussion by howkey666** [nats-io/nats-server#3077] [General]
Hello,
I am trying to write a helm chart for NATS streaming using the fault tolerance mode. In a yaml file specifying a `StatefulSet` I have a few `args` but the important are:

```
"--cluster", "nats://0.0.0.0:{{ .Values.service.clusterPort }}",
"--routes", "nats://{{ .Values.service.name }}:{{ .Values.service.clusterPort }}"]
```

I run 3 replicas so I have 3 pods named `nats-0`, `nats-1` and `nats-2`. 
From a log I can see that nats server on `nats-0` is set as an active and others are in standby mode. When I manually delete the `nats-0` pod then a new active server is elected from the last two servers. That's expected and that meas that they know about each other.

But what is confusing for me is that in a log for particular server I see `x.x.x.x:6222 - rid:6 - Route connection created` where `x.x.x.x` is a `Service` IP and on another line the `x.x.x.x` is a pod IP. In kubernetes we are using IPVS proxy mode https://kubernetes.io/docs/concepts/services-networking/service/#proxy-mode-ipvs and if I understand it correctly, it means that a client (in this case it can be any nats server running within cluster) will not know about a real IP of the pod where it runs but it will know about the `Service` IP only. 
My assumption is that this isn't any problem. But I can be wrong because I don't know how the routing internally works and I were unable to find any resources other then source code.

Is my assumption correct? Can someone write more info about how the routing works? Would be great to have an explanaiton of this proces step by step with some example.

Thank you very much.

**Comment by wallyqs** [comment]
It is recommended that a headless service is used instead when deploying NATS as part of a statefulset and let the NATS Servers and clients to handle the randomizing of the connections. 
Also for TLS and gossip to work, it is needed to set the cluster advertise as part of the NATS configuration as well as to use the `serviceName` setting from the statefulset spec so that each one of the pods have an A record assigned (meaning that the cert has to be a wildcard cert with the name of the service (`*.serviceName.$namespace.svc`)).  For example:

```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: nats
  labels:
    app: nats
spec:
  selector:
    app: nats
  clusterIP: None
  ports:
  - name: client
    port: 4222
  - name: cluster
    port: 6222
  - name: monitor
    port: 8222
  - name: metrics
    port: 7777
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-config
data:
  nats.conf: |
    pid_file: "/var/run/nats/nats.pid"

    http: 8222

    cluster {
      port: 6222
      routes [
        nats://nats:6222
      ]

      cluster_advertise: $CLUSTER_ADVERTISE
      connect_retries: 10
    }
```
As part of the pod spec the cluster advertise setting, you can define the cluster advertise via env vars:

```yaml
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CLUSTER_ADVERTISE
          value: $(POD_NAME).nats.$(POD_NAMESPACE).svc
```

 I have an example here of how to deploy NATS + NATS Streaming as part of a statefulset https://gist.github.com/wallyqs/1f7460072b8cf743b9ff616f0a32007a from which I'll base to make updates to the helm chart soon.
