### DISCUSSION TITLE
Cluster can't tolerate more than one service failure

### DISCUSSION THREAD

**Discussion by AhmedAbouelkher** [nats-io/nats-server#3417] [Q&A] [answered]
Hi,
I'm trying to create a cluster to serve as a messaging queue using pull consumers using docker composer.

### docker-compose.yml
```yaml
version: "3.9"

services:
  nats:
    image: "nats:2.8.4-alpine3.15"
    container_name: nats
    ports:
    - "4222:4222"
    - "8222:8222"
    volumes:
    - ~/Downloads/nats-storage/cluster/jetstream-c1:/tmp/nats/jetstream
    - ./config.c.conf:/config.conf
    command: "--config /config.conf --server_name S1"
    networks:
    - nats

  nats-c2:
    image: "nats:2.8.4-alpine3.15"
    container_name: "nats-c2"
    ports:
    - "5222:4222"
    volumes:
    - ~/Downloads/nats-storage/cluster/jetstream-c2:/tmp/nats/jetstream
    - ./config.c.conf:/config.conf
    command: "--config /config.conf --server_name S2"
    depends_on:
    - nats
    networks:
    - nats

  nats-c3:
    image: "nats:2.8.4-alpine3.15"
    container_name: "nats-c3"
    ports:
    - "6222:4222"
    volumes:
    - ~/Downloads/nats-storage/cluster/jetstream-c3:/tmp/nats/jetstream
    - ./config.c.conf:/config.conf
    command: "--config /config.conf --server_name S3"
    depends_on:
    - nats
    networks:
    - nats

networks:
  nats:
   external: true
```

### config.c.conf

```conf
debug: true
trace: false

http_port: 8222
listen: 0.0.0.0:4222

jetstream = {}

cluster = {
    name: "NATS"

    listen: "0.0.0.0:4123"

    authorization = {
      user: route_user
      password: pwd
      timeout: 5
    }

    routes = [
        nats://route_user:pwd@nats:4123
        nats://route_user:pwd@nats-c2:4123
        nats://route_user:pwd@nats-c3:4123
    ]
}
```

I'm using Golang client version `v1.16.0`.
