### DISCUSSION TITLE
Setting up an embedded cluster

### DISCUSSION THREAD

**Discussion by adoublef** [nats-io/nats-server#4741] [Q&A]
There is a pattern that I would like to experiment with and yet to find any details online.

NATS.io offer:

- Embedding the NATS server into a Go binary
- Creating a cluster of NATS servers.

I would like to know why my current configuration is showing 0 routes. I am unsure how the `routez` option should be set as I have tried hard-coding the network using the docker names (i.e. `nats://go-a:6222`) with no luck. 

```go
func run(ctx context.Context) (err error) {
	ns, err := server.NewServer(&server.Options{
		HTTPPort: 8222,
		Cluster: server.ClusterOpts{
			Name: "NATS",
			Port: 6222,
		},
		RoutesStr: "unsure what to put here",
	})
	if err != nil {
		return err
	}
	defer ns.Shutdown()
	ns.Start()

	select {}
}
```

```yml
version: '3.9'

services:
  go-a:
    container_name: go-a
    build:
      context: .
    ports:
      - 8222:8222
      - 4222:4222
    networks:
      - go-net

  go-b:
    container_name: go-b
    build:
      context: .
    networks:
      - go-net

  go-c:
    container_name: go-c
    build:
      context: .
    networks:
      - go-net

networks:
  go-net:
```

I believe this should work as I did follow the tutorial using external servers and there we have the following 

```bash
docker run -d --name nats-a --network nats --rm -p 4222:4222 -p 8222:8222 nats --http_port 8222 --cluster_name NATS --cluster nats://0.0.0.0:6222
docker run -d --name nats-b --network nats --rm nats --cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats-a:6222
```

Just failing to see how this docker setup translates to an embedded server configuration in Go
