### DISCUSSION TITLE
Authorization and authentication

### DISCUSSION THREAD

**Discussion by Sagarbud** [nats-io/nats-server#5529] [General]
Hello There,

I have installed NATS on GKE cluster using Helm. How we can enable Authorization and authentication?

I have added below auth section in values.yaml file.

auth:
enabled: true
basic:
users:
- user: "admin"
password: "PpZnPE90b3jkH6C"
- user: "appUser"
password: "enGk0cgZUabM6bN6FXHT"

defaultPermissions:
  publish: [">"]
  subscribe: [">"]
When I run the below command and getting the error "nats: error: no results received, ensure the account used has system privileges and appropriate permissions"

nats context add dev-nats --server 10.0.0.1 --description "test dev" --user admin --password pass --select

nats server info

Can you please help me to resolve the issue?

**Comment by ripienaar** [comment]
Try `nats account info` - the `nats server` commands are system accounts and you'll need a system account setup.

Best place to ask these questions are probably in the slack channels

**Comment by Sagarbud** [comment]
Hello @ripienaar 

Thank you for your advice 
I will try your suggestion also

**Comment by caleblloyd** [comment]
The latest Helm Chart specifications are here: https://artifacthub.io/packages/helm/nats/nats

I believe your `values.yaml` should look something like this:

```
config:
  merge:
    authorization:
      default_permissions:
        publish: [">"]
        subscribe:  [">"]
      users:
        user: "admin"
      - password: "PpZnPE90b3jkH6C"
        user: "appUser"
      - password: "enGk0cgZUabM6bN6FXHT"
```

If you'd like, you can join the NATS Slack and ask Kubernetes related questions in the `#k8s` channel: https://natsio.slack.com

**Comment by Sagarbud** [comment]
Hello @caleblloyd 

Thank you for your response!

I have not found config and merge option in values.yaml. Can you please guide me where should i need to add the above portion?

I am using the below NATS version
version=0.19.12

**Reply by caleblloyd** [reply]
That chart version is quite old, if this is a new install I recommend using 1.x. All of the documentation for the chart is here:

https://artifacthub.io/packages/helm/nats/nats

**Comment by Sagarbud** [comment]
Hello @caleblloyd 

I am try to installing NATS version 1.1.12 with below user configuration but getting the error (nats-server: /etc/nats-config/nats.conf:3:6: error parsing accounts: unsupported type map[string]interface {})

    merge:
      accounts:
        A:
          users:
            - user: a
              password: a
        B:
          users:
            - user: b
              password: b

 have referred the URL for the same https://artifacthub.io/packages/helm/nats/nats/1.1.12  Also, I am using the [values.yaml](https://github.com/nats-io/k8s/blob/main/helm/charts/nats/values.yaml#L81)

Can you please guide me how i can configure user and permission for NATS?

Also, I am unable to found node-selector portion in the values.yaml for NATS and nats-box. can you please help me for the same?

**Reply by caleblloyd** [reply]
This works find for me.  Also included node selector example.

```yaml
config:
  merge:
    accounts:
      A:
        users:
        - {user: a, password: a}
      B:
        users:
        - {user: b, password: b}

podTemplate:
  merge:
    spec:
      nodeSelector:
        kubernetes.io/os: linux

natsBox:
  contexts:
    a:
      merge: {user: a, password: a}
    b:
      merge: {user: b, password: b}
  defaultContextName: a

  podTemplate:
    merge:
      spec:
        nodeSelector:
          kubernetes.io/os: linux
```

**Comment by Sagarbud** [comment]
Hello @caleblloyd

Thank you for your support. 

Above section is works for me. Now, I am running the below command to set contexts but getting permission error in nats server info command.

nats context add dev-nats --server 10.250.0.71 --description "test dev" --user a --password a --select
output:
NATS Configuration Context "dev-nats"

      Description: test dev
      Server URLs: 10.250.0.71
         Username: a
         Password: *********
            Token: a
             Path: /home/sagar.bud/.config/nats/context/dev-nats.json
       Connection: OK

nats server info
Output: 
nats: error: no results received, ensure the account used has system privileges and appropriate permissions

Can you help me how i can assign permission to the user?

**Reply by caleblloyd** [reply]
Add a System Account and use that one:

```
config:
  merge:
    system_account: SYS
    accounts:
      A:
        users:
        - {user: a, password: a}
      B:
        users:
        - {user: b, password: b}
      SYS:
        users:
        - {user: sys, password: sys}

podTemplate:
  merge:
    spec:
      nodeSelector:
        kubernetes.io/os: linux

natsBox:
  contexts:
    a:
      merge: {user: a, password: a}
    b:
      merge: {user: b, password: b}
    sys:
      merge: {user: sys, password: sys}
  defaultContextName: sys

  podTemplate:
    merge:
      spec:
        nodeSelector:
          kubernetes.io/os: linux
```
