### DISCUSSION TITLE
Cross account streams using JWT

### DISCUSSION THREAD

**Discussion by zs-ko** [nats-io/nats-server#5619] [Q&A] [answered]
how can we export a stream from one account and import that stream into multiple other accounts using jwt.

Looking at the documentation we have tried a few different ways but it seems that we are doing something wrong. 
in the documentatin we can find the following where account A exports stream b to account b. how would we replicate the following using JWT tokens and NACK streams. 

I am having a hard time to understand the difference between jwt and standard configuration layouts. it ssems that they operate completley different.ly. is there a possibilitiy to add more exmaples on sources, import and exports using jwt and even maybe nack.

Config ex from doc
```
accounts: {
    A: {
        users: [
            {user: a, password: a}
        ]
        exports: [
            {stream: puba.>}
            {service: pubq.>}
            {stream: b.>, accounts: [B]}
            {service: q.b, accounts: [B]}
        ]
    },
    B: {
        users: [
            {user: b, password: b}
        ]
        imports: [
            {stream: {account: A, subject: b.>}}
            {service: {account: A, subject: q.b}}
        ]
    }
    C: {
        users: [
            {user: c, password: c}
        ]
        imports: [
            {stream: {account: A, subject: puba.>}, prefix: from_a}
            {service: {account: A, subject: pubq.C}, to: Q}
        ]
    }
}
```

NACK source stream
```
spec:
  account: A
  allowDirect: false
  allowRollup: false
  compression: ''
  creds: ''
  denyDelete: false
  discard: old
  discardPerSubject: false
  firstSequence: 0
  maxAge: ''
  maxBytes: -1
  maxConsumers: -1
  maxMsgSize: -1
  maxMsgs: -1
  maxMsgsPerSubject: 0
  name: xdr
  nkey: ''
  noAck: false
  preventDelete: false
  preventUpdate: false
  replicas: 1
  retention: limits
  servers: []
  storage: file
  subjects:
    - test.B.sub.>

```

NACK dst stream
```
spec:
  account: B
  allowDirect: false
  allowRollup: false
  compression: ''
  creds: ''
  denyDelete: false
  discard: old
  discardPerSubject: false
  firstSequence: 0
  maxAge: ''
  maxBytes: -1
  maxConsumers: -1
  maxMsgSize: -1
  maxMsgs: -1
  maxMsgsPerSubject: 0
  name: xdr
  nkey: ''
  noAck: false
  preventDelete: false
  preventUpdate: false
  replicas: 1
  retention: limits
  servers: []
  sources:
    - externalApiPrefix: $JS.A.API
      externalDeliverPrefix: B.S
      name: xdr
  storage: file
```
