### DISCUSSION TITLE
Auth Callout in NATS helm chart

### DISCUSSION THREAD

**Discussion by AlexHu0208** [nats-io/nats-server#5620] [Q&A]
Hi team, 

I am trying to config the auth callout in NATS helm chart [values.yaml](https://github.com/nats-io/k8s/blob/main/helm/charts/nats/values.yaml#L306).

In the helm chart, I also configured the resolver and resolver_preload with couple of predefined accounts. 

```
config:
  resolver:
    enabled: true
    merge:
      type: full
      interval: 2m
      timeout: 1.9s
  merge:
    operator: OPERATOR_JWT
    system_account: SYS_ACCOUNT_ID
    resolver_preload:
      SYS_ACCOUNT_ID: SYS_ACCOUNT_JWT
```

When I kick off the deployment, I am seeing the following error https://github.com/nats-io/nats-server/blob/0f0770efe7cef7209828000634e931c3f2181499/server/jwt.go#L158-L160

Is there any way I can keep my resolver configuration but still add the auth callout? I am still learning the NATS, so it can be very helpful if someone can explain why we have this kind of restriction.

Thanks for the help.
