### DISCUSSION TITLE
Client parser ERROR, state=0, i=0: proto='"GET / HTTP/1.1\r\nHost: 172.22.107"...

### DISCUSSION THREAD

**Discussion by xanhz** [nats-io/nats-server#6997] [Q&A]
I'm running NATS cluster in k8s with the following deployment.yaml
```yml
apiVersion: apps/v1
kind: StatefulSet
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: OrderedReady
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nats-jetstream
  serviceName: nats-jetstream
  template:
    spec:
      containers:
        - args:
            - '--config'
            - /etc/nats-config/nats.conf
            - '--jetstream'
            - '--cluster_name=nats-simple-cluster'
            - '--cluster=nats://0.0.0.0:6222'
            - >-
              --routes=nats://nats-simple-jetstream-0.nats-jetstream.nats-simple.svc:6222,nats://nats-simple-jetstream-1.nats-jetstream.nats-simple.svc:6222,nats://nats-simple-jetstream-2.nats-jetstream.nats-simple.svc:6222
            - >-
              --cluster_advertise=$(POD_NAME).nats-simple-jetstream.nats-simple.svc:6222
            - '--server_name=$(POD_NAME)'
          command:
            - nats-server
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: CLUSTER_ADVERTISE
              value: $(POD_NAME).nats-simple-jetstream.nats-simple.svc
          image: bitnami/nats:2.11.4
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sh
                  - '-c'
                  - /nats-server -sl=ldm=/var/run/nats/nats.pid && /bin/sleep 60
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8222
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          name: nats
          ports:
            - containerPort: 4222
              hostPort: 4222
              name: client
              protocol: TCP
            - containerPort: 7422
              hostPort: 7422
              name: leafnodes
              protocol: TCP
            - containerPort: 6222
              name: cluster
              protocol: TCP
            - containerPort: 8222
              name: monitor
              protocol: TCP
            - containerPort: 7777
              name: metrics
              protocol: TCP
            - containerPort: 8080
              name: websocket
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8222
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          resources: {}
          securityContext:
            runAsGroup: 1000
            runAsUser: 1000
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/nats-config
              name: config-volume
            - mountPath: /var/run/nats
              name: pid
            - mountPath: /data
              name: jetstream-data
      dnsPolicy: ClusterFirst
      nodeSelector:
        eks.amazonaws.com/nodegroup: nats-simple
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
        - effect: NoSchedule
          key: nats-simple
          operator: Equal
          value: 'true'
      volumes:
        - configMap:
            defaultMode: 420
            name: nats-jetstream
          name: config-volume
        - emptyDir: {}
          name: pid
        - name: jetstream-data
          persistentVolumeClaim:
            claimName: nat-jetstream-pvc-nfs
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
status:
  availableReplicas: 3
  collisionCount: 0
  currentReplicas: 3
  currentRevision: nats-simple-jetstream-5988d9d859
  observedGeneration: 10
  readyReplicas: 3
  replicas: 3
  updateRevision: nats-simple-jetstream-5988d9d859
  updatedReplicas: 3
```

and nats.conf file
```conf
jetstream {

  store_dir: "/data/jetstream"

  max_mem_store: 1Gb

  max_file_store: 20Gb

}

websocket {

  port: 8080

  no_tls: true

}



pid_file: "/var/run/nats/nats.pid"

http: 8222

debug: false

trace: false

write_deadline: 200s
```

But when running I got this error:
```
nats-simple-jetstream-1 [1] 2025/06/23 04:29:40.863921 [ERR] 172.22.123.218:29836 - cid:913 - Client parser ERROR, state=0, i=0: proto='"GET / HTTP/1.1\r\nHost: 172.22.123"...'
nats-simple-jetstream-2 [1] 2025/06/23 04:29:40.864203 [ERR] 172.22.111.103:3782 - cid:1220 - Client parser ERROR, state=0, i=0: proto='"GET / HTTP/1.1\r\nHost: 172.22.111"...'
nats-simple-jetstream-0 [1] 2025/06/23 04:29:40.959018 [ERR] 172.22.111.103:13373 - cid:675 - Client parser ERROR, state=0, i=0: proto='"GET / HTTP/1.1\r\nHost: 172.22.111"...'
nats-simple-jetstream-0 [1] 2025/06/23 04:29:40.959298 [ERR] 172.22.110.88:7280 - cid:676 - Client parser ERROR, state=0, i=0: proto='"GET / HTTP/1.1\r\nHost: 172.22.110"...'
nats-simple-jetstream-2 [1] 2025/06/23 04:29:40.959092 [ERR] 172.22.123.218:30941 - cid:1221 - Client parser ERROR, state=0, i=0: proto='"GET / HTTP/1.1\r\nHost: 172.22.123"...'
nats-simple-jetstream-2 [1] 2025/06/23 04:29:40.963002 [ERR] 172.22.110.4:22986 - cid:1222 - Client parser ERROR, state=0, i=0: proto='"GET / HTTP/1.1\r\nHost: 172.22.110"...'
nats-simple-jetstream-0 [1] 2025/06/23 04:29:40.963416 [ERR] 172.22.112.100:54628 - cid:677 - Client parser ERROR, state=0, i=0: proto='"GET / HTTP/1.1\r\nHost: 172.22.112"...'
nats-simple-jetstream-2 [1] 2025/06/23 04:29:40.963372 [ERR] 172.22.119.92:49566 - cid:1223 - Client parser ERROR, state=0, i=0: proto='"GET / HTTP/1.1\r\nHost: 172.22.119"...'
nats-simple-jetstream-2 [1] 2025/06/23 04:29:41.159941 [ERR] 172.22.122.62:41477 - cid:1224 - Client parser ERROR, state=0, i=0: proto='"GET / HTTP/1.1\r\nHost: 172.22.122"...'
nats-simple-jetstream-0 [1] 2025/06/23 04:29:41.515626 [ERR] 172.22.119.11:21798 - cid:678 - Client parser ERROR, state=0, i=0: proto='"GET / HTTP/1.1\r\nHost: 172.22.119"...'
nats-simple-jetstream-0 [1] 2025/06/23 04:29:41.528826 [ERR] 172.22.119.11:42117 - cid:679 - Client parser ERROR, state=0, i=0: proto='"GET / HTTP/1.1\r\nHost: 172.22.119"...'
nats-simple-jetstream-0 [1] 2025/06/23 04:29:41.528826 [ERR] 172.22.122.62:11113 - cid:680 - Client parser ERROR, state=0, i=0: proto='"GET / HTTP/1.1\r\nHost: 172.22.122"...'
nats-simple-jetstream-0 [1] 2025/06/23 04:29:41.555189 [INF] 172.22.124.89:26358 - rid:681 - Route connection created
nats-simple-jetstream-0 [1] 2025/06/23 04:29:41.555232 [INF] 172.22.124.89:26358 - rid:681 - Router connection closed: Client Closed
nats-simple-jetstream-2 [1] 2025/06/23 04:29:41.595250 [INF] 172.22.119.11:60090 - rid:1225 - Route connection created
nats-simple-jetstream-2 [1] 2025/06/23 04:29:41.595301 [INF] 172.22.119.11:60090 - rid:1225 - Router connection closed: Client Closed
nats-simple-jetstream-1 [1] 2025/06/23 04:29:41.793269 [INF] 172.22.111.103:16214 - rid:915 - Route connection created
nats-simple-jetstream-1 [1] 2025/06/23 04:29:41.793301 [INF] 172.22.111.103:16214 - rid:915 - Router connection closed: Client Closed
nats-simple-jetstream-0 [1] 2025/06/23 04:29:42.112002 [INF] 172.22.110.88:34234 - rid:682 - Route connection created
nats-simple-jetstream-0 [1] 2025/06/23 04:29:42.112035 [INF] 172.22.110.88:34234 - rid:682 - Router connection closed: Client Closed
nats-simple-jetstream-0 [1] 2025/06/23 04:29:42.329093 [INF] 172.22.112.100:3818 - rid:683 - Route connection created
nats-simple-jetstream-0 [1] 2025/06/23 04:29:42.329285 [INF] 172.22.112.100:3818 - rid:683 - Router connection closed: Client Closed
nats-simple-jetstream-2 [1] 2025/06/23 04:29:42.904435 [INF] 172.22.107.72:65125 - rid:1229 - Route connection created
nats-simple-jetstream-2 [1] 2025/06/23 04:29:42.904549 [INF] 172.22.107.72:65125 - rid:1229 - Router connection closed: Client Closed
nats-simple-jetstream-0 [1] 2025/06/23 04:29:42.922831 [INF] 172.22.106.163:1897 - rid:686 - Route connection created
nats-simple-jetstream-0 [1] 2025/06/23 04:29:42.922861 [INF] 172.22.106.163:1897 - rid:686 - Router connection closed: Client Closed
nats-simple-jetstream-2 [1] 2025/06/23 04:29:43.127351 [INF] 172.22.122.77:53798 - rid:1230 - Route connection created
nats-simple-jetstream-2 [1] 2025/06/23 04:29:43.127399 [INF] 172.22.122.77:53798 - rid:1230 - Router connection closed: Client Closed
nats-simple-jetstream-0 [1] 2025/06/23 04:29:43.156783 [INF] 172.22.119.92:17365 - rid:687 - Route connection created
nats-simple-jetstream-0 [1] 2025/06/23 04:29:43.156812 [INF] 172.22.119.92:17365 - rid:687 - Router connection closed: Client Closed
nats-simple-jetstream-2 [1] 2025/06/23 04:29:43.221285 [INF] 172.22.110.4:61830 - rid:1231 - Route connection created
nats-simple-jetstream-2 [1] 2025/06/23 04:29:43.221376 [INF] 172.22.110.4:61830 - rid:1231 - Router connection closed: Client Closed
nats-simple-jetstream-2 [1] 2025/06/23 04:29:43.265941 [INF] 172.22.126.71:36583 - rid:1232 - Route connection created
nats-simple-jetstream-2 [1] 2025/06/23 04:29:43.265984 [INF] 172.22.126.71:36583 - rid:1232 - Router connection closed: Client Closed
nats-simple-jetstream-1 [1] 2025/06/23 04:29:43.403285 [WRN] RAFT [C1a3NfoN - S-R3F-5PCQRdxS] Request from follower for entry at index [6] errored for state {Msgs:12 Bytes:1202 FirstSeq:1 FirstTime:2025-06-23 04:15:24.688887749 +0000 UTC LastSeq:7 LastTime:2025-06-23 04:25:51.402256939 +0000 UTC NumSubjects:0 Subjects:map[] NumDeleted:0 Deleted:[] Lost:<nil> Consumers:0} - deleted message
nats-simple-jetstream-1 [1] 2025/06/23 04:29:43.403515 [WRN] RAFT [C1a3NfoN - S-R3F-5PCQRdxS] Got an error loading 4 index: deleted message
nats-simple-jetstream-0 [1] 2025/06/23 04:29:43.758447 [INF] 172.22.106.208:18244 - rid:689 - Route connection created
nats-simple-jetstream-0 [1] 2025/06/23 04:29:43.758541 [INF] 172.22.106.208:18244 - rid:689 - Router connection closed: Client Closed
nats-simple-jetstream-0 [1] 2025/06/23 04:29:43.967803 [INF] 172.22.122.62:35052 - rid:690 - Route connection created
nats-simple-jetstream-0 [1] 2025/06/23 04:29:43.967853 [INF] 172.22.122.62:35052 - rid:690 - Router connection closed: Client Closed
nats-simple-jetstream-0 [1] 2025/06/23 04:29:44.009906 [ERR] 172.22.107.72:34868 - cid:691 - Client parser ERROR, state=0, i=0: proto='"GET / HTTP/1.1\r\nHost: 172.22.107"...'
nats-simple-jetstream-2 [1] 2025/06/23 04:29:44.009653 [ERR] 172.22.122.77:36867 - cid:1233 - Client parser ERROR, state=0, i=0: proto='"GET / HTTP/1.1\r\nHost: 172.22.122"...'
nats-simple-jetstream-1 [1] 2025/06/23 04:29:44.012148 [ERR] 172.22.126.71:55700 - cid:920 - Client parser ERROR, state=0, i=0: proto='"GET / HTTP/1.1\r\nHost: 172.22.126"...'
nats-simple-jetstream-0 [1] 2025/06/23 04:29:44.012598 [ERR] 172.22.106.163:46928 - cid:692 - Client parser ERROR, state=0, i=0: proto='"GET / HTTP/1.1\r\nHost: 172.22.106"...'
nats-simple-jetstream-1 [1] 2025/06/23 04:29:44.019178 [INF] 172.22.123.218:20728 - rid:922 - Route connection created
nats-simple-jetstream-1 [1] 2025/06/23 04:29:44.019255 [INF] 172.22.123.218:20728 - rid:922 - Router connection closed: Client Closed
nats-simple-jetstream-2 [1] 2025/06/23 04:29:44.140297 [ERR] 172.22.106.208:52135 - cid:1235 - Client parser ERROR, state=0, i=0: proto='"GET / HTTP/1.1\r\nHost: 172.22.106"...'
nats-simple-jetstream-2 [1] 2025/06/23 04:29:44.140381 [ERR] 172.22.106.163:15964 - cid:1234 - Client parser ERROR, state=0, i=0: proto='"GET / HTTP/1.1\r\nHost: 172.22.106"...'
nats-simple-jetstream-0 [1] 2025/06/23 04:29:44.289285 [ERR] 172.22.106.208:27750 - cid:693 - Client parser ERROR, state=0, i=0: proto='"GET / HTTP/1.1
```
