### ISSUE TITLE
Config reload fails if leafnode remotes are defined

### ISSUE THREAD

**Issue by wallyqs** [nats-io/nats-server#1509]
#### Versions of `nats-server` and affected client libraries used:

2.2.0-beta.19

#### Steps or code to reproduce the issue:

```hcl
port: 4222
http: 8222

cluster {
  port: 6222
  routes: []
}

leafnodes {
  remotes: [
    {
      url: "nats://foo:bar@localhost:7422"
    }
  ]
}
```

#### Expected result:

No op config reload

#### Actual result:

```
[57372] 2020/07/09 10:20:16.654872 [ERR] Failed to reload server configuration: config reload not supported for LeafNode: old={ 0    [] 0 <nil> 0 false  false 1s [0xc0000ca240] <nil> 0 0}, new={ 0    [] 0 <nil> 0 false  false 1s [0xc000302090] <nil> 0 0}
```

**Comment by rolandjitsu** [comment]
I think I'm getting a similar issue on a k8s cluster (no leafnodes):
```
2021-08-23 03:45:15.611 HKT[7] 2021/08/22 19:45:15.611638 [ERR] Failed to reload server configuration: config reload not supported for cluster host: old=, new=0.0.0.0
```

w/ the following helm values:
```yml
---
nats:
  image: nats:2.3.4-alpine
  pullPolicy: IfNotPresent

  # https://docs.nats.io/nats-server/configuration/securing_nats/tls
  tls:
    secret:
      name: nats-server-tls
    ca: "ca.crt"
    cert: "tls.crt"
    key: "tls.key"

cluster:
  enabled: true
  # Cluster name is required, by default will be release name.
  # name: "nats"
  replicas: 3

  # https://github.com/nats-io/k8s/tree/main/helm/charts/nats#using-loadbalancers
  noAdvertise: true

  # tls:
    secret:
      name: nats-server-tls
    ca: "ca.crt"
    cert: "tls.crt"
    key: "tls.key"

natsbox:
  enabled: true
  image: natsio/nats-box:0.6.0
  pullPolicy: IfNotPresent
```
