### ISSUE TITLE
Memory leak in clustered version

### ISSUE THREAD

**Issue by anjmao** [nats-io/nats-server#2474]
## Defect

Make sure that these boxes are checked before submitting your issue -- thank you!

 - [x ] Included `nats-server -DV` output
```
[62] 2021/08/26 19:39:55.648366 [INF] Starting nats-server
[62] 2021/08/26 19:39:55.648553 [INF]   Version:  2.3.4
[62] 2021/08/26 19:39:55.648562 [INF]   Git:      [7112ae0]
[62] 2021/08/26 19:39:55.648569 [DBG]   Go build: go1.16.6
[62] 2021/08/26 19:39:55.648587 [INF]   Name:     NAKA3UC7QQOPLOWAHQMERQGOI5WXBUSTVODVAOLKXEURX3NHY7BQ7KZT
[62] 2021/08/26 19:39:55.648599 [INF]   ID:       NAKA3UC7QQOPLOWAHQMERQGOI5WXBUSTVODVAOLKXEURX3NHY7BQ7KZT
[62] 2021/08/26 19:39:55.648699 [DBG] Created system account: "$SYS"
```
 - [x ] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)
 
Helm chart deployment
```yaml
  nats:
    resources:
      requests:
        cpu: 1
        memory: 2Gi
      limits:
        cpu: 2
        memory: 2Gi

    limits:
      maxConnections:
      maxSubscriptions:
      maxControlLine:
      maxPayload:
      writeDeadline:
      maxPending:
      maxPings:
      lameDuckDuration:

    terminationGracePeriodSeconds: 60

    logging:
      debug:
      trace:
      logtime:
      connectErrorReports:
      reconnectErrorReports:

    jetstream:
      enabled: true

      memStorage:
        enabled: true

      fileStorage:
        enabled: true
        storageDirectory: /data
        storageClassName: standard
        size: 30Gi
        accessModes:
          - ReadWriteOnce

  cluster:
    enabled: true
    replicas: 3
    noAdvertise: false

  auth:
    enabled: true
    systemAccount:
    resolver:
      type: memory
      configMap:
        name: nats-accounts
        key: resolver.conf

  natsbox:
    enabled: false

  exporter:
    enabled: true
```

#### OS/Container environment:
GKE, Kubernetes 1.18

#### Steps or code to reproduce the issue:

Not clear.

#### Expected result:

No memory increase and pod restart

#### Actual result:
<img width="766" alt="Screen Shot 2021-08-26 at 22 43 54" src="https://user-images.githubusercontent.com/3028012/131025906-cc4bed73-9364-4e10-9c02-70360afd8673.png">

<img width="869" alt="Screen Shot 2021-08-26 at 22 47 32" src="https://user-images.githubusercontent.com/3028012/131026376-06717fce-268f-462a-ac41-b9cc30813d74.png">

I believe memory leak is caused for lot of pending entries in RAFT.
```
nats-js-0 nats [139] 2021/08/26 19:51:00.149175 [WRN] RAFT [yLCaJyhQ - S-R3F-gXsNaEaC] 96008 append entries pending
nats-js-0 nats [139] 2021/08/26 19:51:00.150663 [WRN] RAFT [yLCaJyhQ - S-R3F-gXsNaEaC] 96009 append entries pending
nats-js-0 nats [139] 2021/08/26 19:51:00.742236 [WRN] RAFT [yLCaJyhQ - S-R3F-gXsNaEaC] 96010 append entries pending
nats-js-0 nats [139] 2021/08/26 19:51:00.743331 [WRN] RAFT [yLCaJyhQ - S-R3F-gXsNaEaC] 96011 append entries pending
nats-js-0 nats [139] 2021/08/26 19:51:01.022459 [WRN] RAFT [yLCaJyhQ - S-R3F-gXsNaEaC] 96012 append entries pending
nats-js-0 nats [139] 2021/08/26 19:51:01.178187 [WRN] RAFT [yLCaJyhQ - S-R3F-gXsNaEaC] 96013 append entries pending
nats-js-0 nats [139] 2021/08/26 19:51:01.646149 [WRN] Catchup for stream 'AAQE7F2XQY6PODIDHXM6F5MCHTTTYF4N4Z6O6SFGOAA3HCVUHC7J4L4R > agent' stalled
nats-js-0 nats [139] 2021/08/26 19:51:01.680085 [WRN] RAFT [yLCaJyhQ - S-R3F-gXsNaEaC] 96014 append entries pending
nats-js-0 nats [139] 2021/08/26 19:51:01.681182 [WRN] RAFT [yLCaJyhQ - S-R3F-gXsNaEaC] 96015 append entries pending
nats-js-0 nats [139] 2021/08/26 19:51:02.152049 [WRN] RAFT [yLCaJyhQ - S-R3F-gXsNaEaC] 96016 append entries pending
nats-js-0 nats [139] 2021/08/26 19:51:02.153684 [WRN] RAFT [yLCaJyhQ - S-R3F-gXsNaEaC] 96017 append entries pending
```
