### ISSUE TITLE
Consumers stops receiving messages

### ISSUE THREAD

**Issue by anjmao** [nats-io/nats-server#2488]
#### Versions of `nats-server` and affected client libraries used:

Nats server version
```
[83] 2021/09/04 18:51:12.239432 [INF] Starting nats-server
[83] 2021/09/04 18:51:12.239488 [INF]   Version:  2.4.0
[83] 2021/09/04 18:51:12.239494 [INF]   Git:      [219a7c98]
[83] 2021/09/04 18:51:12.239496 [DBG]   Go build: go1.16.7
[83] 2021/09/04 18:51:12.239517 [INF]   Name:     NBVE7O7DMRAZ63STC7Z644KHF5HJ6QQUGLZVGDIKEG32CFL2J6O2456M
[83] 2021/09/04 18:51:12.239533 [INF]   ID:       NBVE7O7DMRAZ63STC7Z644KHF5HJ6QQUGLZVGDIKEG32CFL2J6O2456M
[83] 2021/09/04 18:51:12.239605 [DBG] Created system account: "$SYS"
```

Go client version: `v1.12.0`

#### OS/Container environment:

GKE Kubernetes. Running nats js HA cluster. Deployed via nats helm chart.

#### Steps or code to reproduce the issue:

Stream configuration:
```yaml
apiVersion: jetstream.nats.io/v1beta1
kind: Stream
metadata:
  name: agent
spec:
  name: agent
  subjects: ["data.*"]
  storage: file
  maxAge: 1h
  replicas: 3
  retention: interest
```

There are two consumers to this stream. Each runs as queue subscriber in two services with 2 pod replicas. Note that I don't care if message is not processed, this is why ack none is set.
```go

// 2 pods for service A.
js.QueueSubscribe(
	"data.received",
	"service1_queue",
	func(msg *nats.Msg) {},
	nats.DeliverNew(),
	nats.AckNone(),
)

// 2 pods for service B.
s.js.QueueSubscribe(
	"data.received",
	"service2_queue",
	func(msg *nats.Msg) {},
	nats.DeliverNew(),
	nats.AckNone(),
)
```

#### Expected result:

Consumer receives messages.

#### Actual result:

Stream stats after few days:

```
agent                  │ File    │ 3         │ 28,258   │ 18 MiB  │ 0    │ 84      │ nats-js-0, nats-js-1*, nats-js-2
```

Consumers stats:

```
service1_queue │ Push │ None       │ 0.00s    │ 0           │ 0           │ 0           │ 60,756    │ nats-js-0, nats-js-1*, nats-js-2
service2_queue │ Push │ None       │ 0.00s    │ 0           │ 0           │ 8,193 / 28% │ 60,843    │ nats-js-0, nats-js-1*, nats-js-2
```

1. Non of the nats server pods contains errors indicating any problem.
2. Unprocessed messages count for second consumer stays the same and doesn't decrease.
3. The only fix which helped is after I changed second consumer raft leader with `nats consumer cluster step-down`. But after some time problem still comes back.
4. There are active connections to the server. Checked with `nats server report connections`.

/cc @kozlovic @derekcollison

**Comment by izarraga** [comment]
I think i have the same problem.

Server 2.4 (standalone) and go client 1.12.1 have worked well for 3 days and suddenly consumer have stops receiving messages.

**Comment by derekcollison** [comment]
What does the nats cli report for your consumer?

`nats consumer info`

**Comment by tigrato** [comment]
I also have the same issue and the nats consumer info didn't report anything wrong except high number of Unprocessed Messages

**Comment by izarraga** [comment]
Now it is working because i have restart it.  I supose you need this information when appear the problem.


root@pagasarri:/usr/src/natscli/nats# ./nats -s nats://192.168.109.177:4222 consumer info
? Select a Stream aikodb
? Select a Consumer durableDBcode
Information for Consumer aikodb > durableDBcode created 2021-09-05T23:31:48+02:00

Configuration:

        Durable Name: durableDBcode
           Pull Mode: true
      Filter Subject: aiko-dbcode-q
      Deliver Policy: All
          Ack Policy: Explicit
            Ack Wait: 30s
       Replay Policy: Instant
  Maximum Deliveries: 10000
     Max Ack Pending: 65,536
   Max Waiting Pulls: 512

State:

   Last Delivered Message: Consumer sequence: 5730 Stream sequence: 156257 Last delivery: 54.91s ago
     Acknowledgment floor: Consumer sequence: 5730 Stream sequence: 155997 Last Ack: 54.91s ago
         Outstanding Acks: 0 out of maximum 65536
     Redelivered Messages: 0
     Unprocessed Messages: 0
            Waiting Pulls: 1 of maximum 512

**Comment by derekcollison** [comment]
I think in this case and maybe above its due to requests for new messages not having the expiration time on it so server holds onto them and they build up and you will reach maximum of 512 so no new requests will be received and the existing ones can not expire.

This has been fixed in the Go client, so maybe take a quick peek at the latest client there.

**Comment by tigrato** [comment]
On my case it was not the issue. I tested with the latest Go client v1.12.1 both at publisher and subscriber, server is running v2.4.0  and the issue was still happening.
```
Information for Consumer DB > call_db created 2021-09-06T14:11:26+01:00

Configuration:

        Durable Name: call_db
    Delivery Subject: _INBOX.3aXsLI9XmM6LsZkiynMv69
      Filter Subject: db.clients
        Deliver Next: true
          Ack Policy: Explicit
            Ack Wait: 1m0s
       Replay Policy: Instant
     Max Ack Pending: 40
        Flow Control: false

Cluster Information:

                Name: nats
              Leader: nats-2
             Replica: nats-1, current, seen 0.03s ago

State:

   Last Delivered Message: Consumer sequence: 481038 Stream sequence: 484177
     Acknowledgment floor: Consumer sequence: 481038 Stream sequence: 484177
         Outstanding Acks: 0 out of maximum 40
     Redelivered Messages: 0
     Unprocessed Messages: 1```

and stream info 


Information for Consumer DB > error_db created 2021-09-06T14:11:26+01:00

Configuration:

        Durable Name: error_db
    Delivery Subject: _INBOX.3aXsLI9XmM6LsZkiynMv69
      Filter Subject: db.errors
        Deliver Next: true
          Ack Policy: Explicit
            Ack Wait: 1m0s
       Replay Policy: Instant
     Max Ack Pending: 40
        Flow Control: false

Cluster Information:

                Name: nats
              Leader: nats-2
             Replica: nats-1, current, seen 0.03s ago

State:

   Last Delivered Message: Consumer sequence: 1915 Stream sequence: 484177
     Acknowledgment floor: Consumer sequence: 1915 Stream sequence: 484177
         Outstanding Acks: 0 out of maximum 40
     Redelivered Messages: 0
     Unprocessed Messages: 1```

and stream info 
```

Information for Stream DB created 2021-09-06T14:11:23+01:00

Configuration:

             Subjects: db.*
     Acknowledgements: true
            Retention: File - Interest
             Replicas: 2
       Discard Policy: Old
     Duplicate Window: 2m0s
     Maximum Messages: unlimited
        Maximum Bytes: 1.0 GiB
          Maximum Age: 8h0m0s
 Maximum Message Size: 5.8 MiB
    Maximum Consumers: unlimited


Cluster Information:

                 Name: nats
               Leader: nats-1
              Replica: nats-2, current, seen 0.06s ago

State:

             Messages: 352
                Bytes: 51 KiB
             FirstSeq: 325 @ 2021-09-06T13:11:26 UTC
              LastSeq: 492,161 @ 2021-09-06T17:43:09 UTC
     Deleted Messages: 491485
     Active Consumers: 2
```

One thing I saw is that the number of Messages in the stream starts to increase (now it's just 352 but increments from time to time) and the consumer stops consuming them, leaving the queue subscribers starving for new messages. The messages are not delivered at all.

**Comment by derekcollison** [comment]
Why so many deleted messages?

**Comment by tigrato** [comment]
Tbh I thought it was the default behaviour after consuming the message with Ack.
Under which conditions should  the messages be deleted?

**Comment by anjmao** [comment]
I was able to reproduce locally with docker-compose:


```go
_, err := js.AddStream(&nats.StreamConfig{
	Name:      "cluster",
	Subjects:  []string{"cluster.*"},
	Retention: nats.InterestPolicy,
	Discard:   nats.DiscardOld,
	MaxAge:    1 * time.Minute,
	Storage:   nats.FileStorage,
	Replicas:  3,
})
it.NoError(err)

// Some test file with 144kb data.
b, err := ioutil.ReadFile("generated.yaml")
it.NoError(err)

_, err = js.QueueSubscribe("cluster.created", "test_cluster_created", func(msg *nats.Msg) {
}, nats.DeliverNew(),
	nats.AckNone())
it.NoError(err)

_, err = js.QueueSubscribe("cluster.created", "test_cluster_created", func(msg *nats.Msg) {
}, nats.DeliverNew(),
	nats.AckNone())
it.NoError(err)

_, err = js.QueueSubscribe("cluster.created", "test2_cluster_created", func(msg *nats.Msg) {
}, nats.DeliverNew(),
	nats.AckNone())
it.NoError(err)

_, err = js.QueueSubscribe("cluster.created", "test2_cluster_created", func(msg *nats.Msg) {
}, nats.DeliverNew(),
	nats.AckNone())
it.NoError(err)

for {
	_, err = js.Publish("cluster.created", b)
	it.NoError(err)
	time.Sleep(100 * time.Microsecond)
}
```

```yaml
version: '3'
services:
  n1:
    container_name: n1
    image: nats:2.4.0-alpine
    entrypoint: /usr/local/bin/nats-server
    command: "--config /config/jetstream.conf --server_name S1"
    networks:
      - nats
    ports:
      - 4222:4222
    volumes:
      - ./config:/config
      - ./persistent-data/server-n1/:/data/nats-server/jetstream

  n2:
    container_name: n2
    image: nats:2.4.0-alpine
    entrypoint: /usr/local/bin/nats-server
    command: "--config /config/jetstream.conf --server_name S2"
    networks:
      - nats
    ports:
      - 4223:4222
    volumes:
      - ./config:/config
      - ./persistent-data/server-n2/:/data/nats-server/jetstream

  n3:
    container_name: n3
    image: nats:2.4.0-alpine
    entrypoint: /usr/local/bin/nats-server
    command: "--config /config/jetstream.conf --server_name S3"
    networks:
      - nats
    ports:
      - 4224:4222
    volumes:
      - ./config:/config
      - ./persistent-data/server-n3/:/data/nats-server/jetstream

networks:
  nats: {}
  
```

config
```
debug: true
trace: false

# Each server can connect to clients on the internal port 4222
# (mapped to external ports in our docker-compose)
port: 4222

# Persistent JetStream data store
jetstream = {
  # Each server persists messages within the docker container
  # at /data/nats-server (mounted as ./persistent-data/server-n…
  # in our docker-compose)
  store_dir: "/data/nats-server/"
}

# Cluster formation
cluster = {
  name: "JSC"
  listen: "0.0.0.0:4245"

  # Servers can connect to one another at
  # the following routes
  routes = [
    "nats://n1:4245"
    "nats://n2:4245"
    "nats://n3:4245"
  ]
}

accounts: {
  SYS: { users: [ {user: "admin", password: "admin"} ] },
}
system_account: SYS
```

First I tried publishing each millisecond. Seems to work. Decreased to 100 microseconds and waited 1 minute until stream age retention kicks in. One consumer got `298 / 2%` unprocessed and was not able to catchup even after publish was disabled. 

Is is possible that at some point consumer is not able to catchup for short period of time(which is normal), but since old messages are removed by be retention unprocessed counter is never decreased for whose consumers?

**Comment by ripienaar** [comment]
What I can reproduce is this:

From Stream info:

```
Configuration:
...
            Retention: File - Interest
...

State:
             Messages: 1,515
```

This number jumps around a bit and sometimes just grows like on every message.

Confusingly this is a "interest" retention so really if I delete the consumer these messages should go away, they dont though. I've also seen huge `Deleted` numbers between stops and starts of the test code

At that time the consumer has:

```
State:

   Last Delivered Message: Consumer sequence: 151209 Stream sequence: 151288 Last delivery: 0.01s ago
     Unprocessed Messages: 30
          Active Interest: Active using Queue Group test_cluster_created
```

Only 30 unprocessed? There's a definite disconnect between realities here from the perspective of stream and consumer.

However, these consumers do not stall, even if the stream numbers grow and grow, with 10 active consumers and a bit of tracking added to your code above:

```
<------------
Worker 0: 16168
Worker 1: 15936
Worker 2: 16458
Worker 3: 16031
Worker 4: 16106
Worker 5: 16159
Worker 6: 16268
Worker 7: 16202
Worker 8: 15975
Worker 9: 16249
13:22:24: 161552
...
<------------
Worker 0: 17449
Worker 1: 17225
Worker 2: 17723
Worker 3: 17429
Worker 4: 17472
Worker 5: 17400
Worker 6: 17580
Worker 7: 17455
Worker 8: 17235
Worker 9: 17605
13:23:39: 174573
```

And there's a good growth over time regardless of this, so I think we might have a case with some messages being orphaned somewhre but the consumer is still functioning at a basic level despite the numbers in stream/consumer info being wonky

**Comment by tigrato** [comment]
I stalled consumers after a while with a setup similar to the one described by @anjmao  but with multiple producers.
```Information for Consumer cluster > test_cluster_created created 2021-09-07T18:08:27+01:00

Configuration:

        Durable Name: test_cluster_created
    Delivery Subject: _INBOX.6cLvc4IkqMyshQIhT87UNO
      Filter Subject: cluster.created
         Deliver All: true
          Ack Policy: Explicit
            Ack Wait: 30s
       Replay Policy: Instant
     Max Ack Pending: 20
        Flow Control: false

Cluster Information:

                Name: JSC
              Leader: S3
             Replica: S2, current, seen 0.04s ago

State:

   Last Delivered Message: Consumer sequence: 164587 Stream sequence: 321207
     Acknowledgment floor: Consumer sequence: 164587 Stream sequence: 321207
         Outstanding Acks: 0 out of maximum 20
     Redelivered Messages: 0
     Unprocessed Messages: 0```
     
     While the stream:
     ```Information for Stream cluster created 2021-09-07T18:08:27+01:00

Configuration:

             Subjects: cluster.*
     Acknowledgements: true
            Retention: File - Interest
             Replicas: 2
       Discard Policy: Old
     Duplicate Window: 2m0s
     Maximum Messages: unlimited
        Maximum Bytes: 1.0 GiB
          Maximum Age: 8h0m0s
 Maximum Message Size: 5.8 MiB
    Maximum Consumers: unlimited


Cluster Information:

                 Name: JSC
               Leader: S3
              Replica: S2, current, seen 0.00s ago

State:

             Messages: 93,941
                Bytes: 96 MiB
             FirstSeq: 121,672
              LastSeq: 321,207 @ 2021-09-07T17:57:32 UTC
     Deleted Messages: 199
     Active Consumers: 2``` 
     
     Those 93k messages were never deliver to the subscribers and the consumer becomes stalled

**Comment by kozlovic** [comment]
You also need to make sure that the internal NATS subscriptions are not dropping messages due to being a slow consumer. So I would strongly recommend that you setup an "error handler" on the connection and report if any error is found there.

**Comment by derekcollison** [comment]
Also please make sure you are running latest from main branch as we continue to merge PRs etc.. Thanks!

**Comment by tigrato** [comment]
@derekcollison,
Sorry to bother again but the issue persists even for the current `main` branch.

The issue happens when the consumers are slow to handle all the messages that are being published to the STREAM.
I have 10 publishers and 5 queue subscriptions and for a while the subscribers receive messages but after a while the subscribers receive no error and stops receiving messages while the publishers continue to push until JetStream becomes unavailable.

```go

package main

import (
	"fmt"
	"sync/atomic"
	"time"

	"github.com/nats-io/nats.go"
)

func main() {
	c2, err := nats.Connect("nats://192.168.1.200:4222")
	if err != nil {
		panic(err)
	}
	js2, err := c2.JetStream()
	if err != nil {
		panic(err)
	}
	recivedMsg := new(int64)
	publishedMsg := new(int64)
	go func() {
		t := time.NewTicker(5 * time.Second)
		var receivedOldMsg int64

		var publishedOldMsg int64

		for range t.C {
			receivedMsg := atomic.LoadInt64(recivedMsg)
			publishedMsg := atomic.LoadInt64(publishedMsg)
			fmt.Println("received", receivedMsg-receivedOldMsg, "published", publishedMsg-publishedOldMsg)
			receivedOldMsg = receivedMsg
			publishedOldMsg = publishedMsg
		}
	}()
	_, err = js2.AddStream(&nats.StreamConfig{
		Name:         "cluster",
		Subjects:     []string{"cluster.*"},
		Retention:    nats.InterestPolicy,
		Discard:      nats.DiscardOld,
		MaxAge:       8 * time.Hour,
		Storage:      nats.FileStorage,
		MaxConsumers: 0,
		MaxMsgs:      0,
		MaxBytes:     1073741824,

		MaxMsgSize: 6048576,

		Replicas: 2,
	})
	if err != nil {
		fmt.Println(err)
	}
	inbox := nats.NewInbox()
	_, err = js2.AddConsumer("cluster", &nats.ConsumerConfig{
		Durable:        "test_cluster_created",
		DeliverGroup:   "test_cluster_created",
		DeliverSubject: inbox,
		DeliverPolicy:  nats.DeliverAllPolicy,
		FilterSubject:  "cluster.created",
		AckPolicy:      nats.AckExplicitPolicy,
		AckWait:        60000000000,
		MaxAckPending:  40,
		//MaxWaiting:     5000,
	})

	if err != nil {
		panic(err)
	}
	inbox = nats.NewInbox()

	_, err = js2.AddConsumer(
		"cluster",
		&nats.ConsumerConfig{
			Durable:        "test2_cluster_created",
			DeliverGroup:   "test2_cluster_created",
			DeliverSubject: inbox,
			DeliverPolicy:  nats.DeliverAllPolicy,
			FilterSubject:  "cluster.sapo",
			AckPolicy:      nats.AckExplicitPolicy,
			AckWait:        60000000000,
			MaxAckPending:  40,
			//MaxWaiting:     5000,
		},
	)
	if err != nil {
		panic(err)
	}
	for i := 0; i < 5; i++ {

		go func() {

			c, err := nats.Connect("nats://192.168.1.200:4222", nats.ErrorHandler(func(c *nats.Conn, s *nats.Subscription, e error) {

				if err != nil {
					fmt.Println("slow", err)
				}

			}), nats.DisconnectErrHandler(func(c *nats.Conn, e error) {
				if err != nil {
					fmt.Println("slow2", err)
				}

			}),
				nats.DisconnectHandler(func(c *nats.Conn) {
					fmt.Println("disconnected")
				}),
			)
			if err != nil {
				panic(err)
			}
			js, err := c.JetStream()
			if err != nil {
				panic(err)
			}
		
			_, err = js.QueueSubscribe(
				"cluster.created",
				"test_cluster_created",
				func(msg *nats.Msg) {
					time.Sleep(50 * time.Millisecond)
					msg.Ack()
					atomic.AddInt64(recivedMsg, 1)
				},
				nats.ManualAck(),
				nats.Bind("cluster", "test_cluster_created"),
			)
			if err != nil {
				panic(err)
			}

			_, err = js.QueueSubscribe("cluster.sapo", "test2_cluster_created",
				func(msg *nats.Msg) {
					//	msg.InProgress(nats.AckWait(45 * time.Second))
					time.Sleep(50 * time.Millisecond)
					msg.Ack()
					atomic.AddInt64(recivedMsg, 1)
				},
				nats.ManualAck(),
				nats.Bind("cluster", "test2_cluster_created"),
			)
			if err != nil {
				panic(err)
			}

		}()
	}
	time.Sleep(5 * time.Second)
	for i := 0; i < 15; i++ {
		go func() {
			b := make([]byte, 6500)
			for i := 0; i < len(b); i++ {
				b[i] = byte(i % 256)
			}
			c, err := nats.Connect("nats://192.168.1.200:4222")
			if err != nil {
				panic(err)
			}
			js, err := c.JetStream()
			if err != nil {
				panic(err)
			}
			for {
				_, err = js.Publish("cluster.created", b)
				if err != nil {
					fmt.Println(err)
				}
			
				atomic.AddInt64(publishedMsg, 1)
			}
		}()
	}

	time.Sleep(50 * time.Minute)
}


```

**Comment by derekcollison** [comment]
This running against a single server? What does the config look like?

**Comment by tigrato** [comment]
> This running against a single server? What does the config look like?

This is running against the config that @anjmao provided earlier but  instead of v2.4 I am running agains the master.
```
version: '3'
services:
  n1:
    container_name: n1
    image: nats:2.4.0-alpine
    entrypoint: /usr/local/bin/nats-server
    command: "--config /config/jetstream.conf --server_name S1"
    networks:
      - nats
    ports:
      - 4222:4222
    volumes:
      - ./config:/config
      - ./persistent-data/server-n1/:/data/nats-server/jetstream

  n2:
    container_name: n2
    image: nats:2.4.0-alpine
    entrypoint: /usr/local/bin/nats-server
    command: "--config /config/jetstream.conf --server_name S2"
    networks:
      - nats
    ports:
      - 4223:4222
    volumes:
      - ./config:/config
      - ./persistent-data/server-n2/:/data/nats-server/jetstream

  n3:
    container_name: n3
    image: nats:2.4.0-alpine
    entrypoint: /usr/local/bin/nats-server
    command: "--config /config/jetstream.conf --server_name S3"
    networks:
      - nats
    ports:
      - 4224:4222
    volumes:
      - ./config:/config
      - ./persistent-data/server-n3/:/data/nats-server/jetstream

networks:
  nats: {}
 ```
config

```
debug: true
trace: false

# Each server can connect to clients on the internal port 4222
# (mapped to external ports in our docker-compose)
port: 4222

# Persistent JetStream data store
jetstream = {
  # Each server persists messages within the docker container
  # at /data/nats-server (mounted as ./persistent-data/server-n…
  # in our docker-compose)
  store_dir: "/data/nats-server/"
}

# Cluster formation
cluster = {
  name: "JSC"
  listen: "0.0.0.0:4245"

  # Servers can connect to one another at
  # the following routes
  routes = [
    "nats://n1:4245"
    "nats://n2:4245"
    "nats://n3:4245"
  ]
}

accounts: {
  SYS: { users: [ {user: "admin", password: "admin"} ] },
}
system_account: SYS

```
