### ISSUE TITLE
In memory storage memory leak

### ISSUE THREAD

**Issue by anjmao** [nats-io/nats-server#2548]
## Defect

Make sure that these boxes are checked before submitting your issue -- thank you!

 - [x] Included `nats-server -DV` output
 - [x] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

#### Versions of `nats-server` and affected client libraries used:

Server: docker.io/synadia/nats-server:nightly-20210920
Go client: v1.12.0

#### OS/Container environment:
Docker

#### Steps or code to reproduce the issue:

docker-compose.yam for clustered mode server
```yaml
version: '3'
services:
  n1:
    container_name: n1
    image: docker.io/synadia/nats-server:nightly-20210920
    entrypoint: /bin/nats-server
    command: "--config /config/jetstream.conf --server_name S1 --profile 6060"
    networks:
      - nats
    ports:
      - 4222:4222
      - 6061:6060
    volumes:
      - ./config:/config
      - ./persistent-data/server-n1/:/data/nats-server/jetstream

  n2:
    container_name: n2
    image: docker.io/synadia/nats-server:nightly-20210920
    entrypoint: /bin/nats-server
    command: "--config /config/jetstream.conf --server_name S2 --profile 6060"
    networks:
      - nats
    ports:
      - 4223:4222
      - 6062:6060
    volumes:
      - ./config:/config
      - ./persistent-data/server-n2/:/data/nats-server/jetstream

  n3:
    container_name: n3
    image: docker.io/synadia/nats-server:nightly-20210920
    entrypoint: /bin/nats-server
    command: "--config /config/jetstream.conf --server_name S3 --profile 6060"
    networks:
      - nats
    ports:
      - 4224:4222
      - 6063:6060
    volumes:
      - ./config:/config
      - ./persistent-data/server-n3/:/data/nats-server/jetstream

networks:
  nats: {}
```

Test case

```go
js.AddStream(&nats.StreamConfig{
	Name:      "memory-leak",
	Subjects:  []string{"memory-leak"},
	Retention: nats.LimitsPolicy,
	MaxMsgs:   1000,
	Discard:   nats.DiscardOld,
	MaxAge:    time.Minute,
	Storage:   nats.MemoryStorage,
	Replicas:  3,
})

_, _ = js.QueueSubscribe("memory-leak", "q1", func(msg *nats.Msg) {
	fmt.Println("recv")
	time.Sleep(1 * time.Second)
	msg.Ack()
})

msg := []byte("NATS is a connective technology that powers modern distributed systems.")
for {
	_, err := js.Publish("memory-leak", msg)
	if err != nil {
              panic(err)
        }
	fmt.Println("pub")
}
```

Stream report
```
╭──────────────────────────────────────────────────────────────────────────────────────╮
│                                    Stream Report                                     │
├─────────────┬─────────┬───────────┬──────────┬────────┬──────┬─────────┬─────────────┤
│ Stream      │ Storage │ Consumers │ Messages │ Bytes  │ Lost │ Deleted │ Replicas    │
├─────────────┼─────────┼───────────┼──────────┼────────┼──────┼─────────┼─────────────┤
│ memory-leak │ Memory  │ 1         │ 1,000    │ 96 KiB │ 0    │ 0       │ S1, S2*, S3 │
╰─────────────┴─────────┴───────────┴──────────┴────────┴──────┴─────────┴─────────────╯
```

Consumer report
```
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                              Consumer report for memory-leak with 1 consumers                               │
├──────────┬──────┬────────────┬──────────┬─────────────┬─────────────┬─────────────┬───────────┬─────────────┤
│ Consumer │ Mode │ Ack Policy │ Ack Wait │ Ack Pending │ Redelivered │ Unprocessed │ Ack Floor │ Cluster     │
├──────────┼──────┼────────────┼──────────┼─────────────┼─────────────┼─────────────┼───────────┼─────────────┤
│ q1       │ Push │ Explicit   │ 30.00s   │ 1,000       │ 0           │ 0           │ 201,486   │ S1, S2*, S3 │
╰──────────┴──────┴────────────┴──────────┴─────────────┴─────────────┴─────────────┴───────────┴─────────────╯
```

Memory profile

![profile003](https://user-images.githubusercontent.com/3028012/134068344-f5e96a77-d394-415a-a477-2de78c5e4ad8.png)

#### Expected result:

Memory doesn't increase. Actual stream size is only 96KiB, but keeps increasing.

#### Actual result:

It looks that old messages are not removed from the memory store and has something to do with consumer which is not able to keep up with message rate. I tried publishing messages without active consumers. In such case there is no problem.

Maybe it could be related to some bug in `return ms.removeMsg(ms.state.FirstSeq, false)` as messages are removed by `ms.state.FirstSeq` index.
