### ISSUE TITLE
Nats Jetstream dies after many open connections

### ISSUE THREAD

**Issue by nfoerster** [nats-io/nats-server#2574]
## Defect

Not sure what happened. We had an application leaking connections to NATS, however, at a later point in time, it has a huge number of reconnection issues to the cluster itself before it stops. From this time on no external communication is further possible. At the moment we don't have a reproducible example.

Nats Version: nats:2.6.0-alpine
Nats Client: Nats Go 1.12.3

We deploy with helm, this is the values.yml diff to default:
```
nats:
  image: nats:2.6.0-alpine

  resources:
    requests:
      memory: "1Gi"
      cpu: "250m" 
    limits:
      memory: "2Gi"
      cpu: "1000m" 

  jetstream:
    enabled: true

    memStorage:
      enabled: true
      size: "1Gi" #must be lower equals resource limits!

    fileStorage:
      enabled: true
      size: "50Gi"
      storageDirectory: /data/
      # storageClassName: do-block-storage
    
affinity: 
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - topologyKey: "kubernetes.io/hostname"

cluster:
  enabled: true
  name: nats
  replicas: 3
```

Nats Cluster Configuration:

```
    ###############
    #             #
    # Monitoring  #
    #             #
    ###############
    http: 8222
    server_name: $POD_NAME
    ###################################
    #                                 #
    # NATS JetStream                  #
    #                                 #
    ###################################
    jetstream {
      max_mem: 1Gi
      store_dir: /data/

      max_file:50Gi
    }
    ###################################
    #                                 #
    # NATS Full Mesh Clustering Setup #
    #                                 #
    ###################################
    cluster {
      port: 6222
      name: nats

      routes = [
        nats://nats-jet-0.nats-jet.nats.svc.cluster.local.:6222,nats://nats-jet-1.nats-jet.nats.svc.cluster.local.:6222,nats://nats-jet-2.nats-jet.nats.svc.cluster.local.:6222,
      ]
      cluster_advertise: $CLUSTER_ADVERTISE

      connect_retries: 30
    }
```

Nats Cluster Logs attached.
[nats-nats-jet-1-1632726192528760345.log](https://github.com/nats-io/nats-server/files/7234151/nats-nats-jet-1-1632726192528760345.log)
[nats-nats-jet-2-1632726166458455522.log](https://github.com/nats-io/nats-server/files/7234152/nats-nats-jet-2-1632726166458455522.log)
[nats-nats-jet-0-1632726221020311157.log](https://github.com/nats-io/nats-server/files/7234153/nats-nats-jet-0-1632726221020311157.log)
