### ISSUE TITLE
NATS doesn't honor container limits

### ISSUE THREAD

**Issue by aksdb** [nats-io/nats-server#2586]
#### Versions of `nats-server` and affected client libraries used:

Server Image: nats:2.6.1-alpine

#### OS/Container environment:

Kubernetes

#### Steps or code to reproduce the issue:

Run NATS (Helm Chart 0.8.9) with resource limits on CPU (on a machine with more CPU cores than that):

```
      resources:
        limits:
          cpu: 1
        requests:
          cpu: 1
```

Check `nats_varz_gomaxprocs`.

#### Expected result:

`nats_varz_gomaxprocs` is 1 (as this is the limit).

#### Actual result:

`nats_varz_gomaxprocs` is 16 (in my case; since the CPU has 16 threads).

#### Additional notes

I think it might be as easy as including (and invoking) this library: https://github.com/uber-go/automaxprocs
Then `GOMAXPROCS` will be adjusted according to potential container limits.
