### ISSUE TITLE
Can't keep Jetstream cluster working when execute rolling upgrade from 2.5.0 to 2.7.4

### ISSUE THREAD

**Issue by phho** [nats-io/nats-server#2935]
#### Versions of `nats-server` and affected client libraries used:
- nats-server 2.7.4
- nats helm chart 0.14.2
#### OS/Container environment:
- K8s
#### Steps or code to reproduce the issue:
1. Existing nats 2.5.0 cluster (5 instances) with Jetstream enabled
2. Configure `podManagementPolicy: OrderedReady` ( https://github.com/nats-io/k8s/tree/main/helm/charts/nats#breaking-change-log ) for old helm chart deployment compatible
3. When execute rolling upgrade to 2.7.4 on ordinal 4 and ordinal 3 pod. Ordinal 2, 1, and 0 (those 3 pods still in old version 2.5.0) nats pod process start panic with following error logs and can't continue to upgrade. NATS cluster can't form a Jetstream meta Group due to only have two servers alive.
```
[1652] 2022/03/21 02:49:11.632347 [INF] Listening for route connections on [0.0.0.0:6222](http://0.0.0.0:6222/)
[1652] 2022/03/21 02:49:11.633565 [INF]…:6222 - rid:225 - Route connection created
[1652] 2022/03/21 02:49:11.633658 [INF] …:6222 - rid:226 - Route connection created
[1652] 2022/03/21 02:49:11.633736 [INF] …:6222 - rid:227 - Route connection created
[1652] 2022/03/21 02:49:11.633760 [INF] …:6222 - rid:228 - Route connection created
panic: JetStream Cluster Unknown group entry op type! 12
goroutine 284 [running]:
[github.com/nats-io/nats-server/server.(*jetStream).applyConsumerEntries(0xc0002d4000](http://github.com/nats-io/nats-server/server.(*jetStream).applyConsumerEntries(0xc0002d4000), 0xc000445c00, 0xc001ef6940, 0x0, 0x5, 0x1)
        /home/travis/gopath/src/[github.com/nats-io/nats-server/server/jetstream_cluster.go:2948](http://github.com/nats-io/nats-server/server/jetstream_cluster.go:2948) +0x5e7
[github.com/nats-io/nats-server/server.(*jetStream).monitorConsumer(0xc0002d4000](http://github.com/nats-io/nats-server/server.(*jetStream).monitorConsumer(0xc0002d4000), 0xc000445c00, 0xc000cbb0e0)
        /home/travis/gopath/src/[github.com/nats-io/nats-server/server/jetstream_cluster.go:2874](http://github.com/nats-io/nats-server/server/jetstream_cluster.go:2874) +0x65f
[github.com/nats-io/nats-server/server.(*jetStream).processClusterCreateConsumer.func1()](http://github.com/nats-io/nats-server/server.(*jetStream).processClusterCreateConsumer.func1())
        /home/travis/gopath/src/[github.com/nats-io/nats-server/server/jetstream_cluster.go:2691](http://github.com/nats-io/nats-server/server/jetstream_cluster.go:2691) +0x3c
created by [github.com/nats-io/nats-server/server.(*Server).startGoRoutine](http://github.com/nats-io/nats-server/server.(*Server).startGoRoutine)
        /home/travis/gopath/src/[github.com/nats-io/nats-server/server/server.go:2867](http://github.com/nats-io/nats-server/server/server.go:2867) +0xc5
```

**Comment by changtimwu** [comment]
@phho  could you provide the values files given to `helm install` of 2.5.0 and `helm upgrade` of 2.7.4?
 like the way [this issue being reported](https://github.com/nats-io/k8s/issues/312)

Based on your description, it seems that the first pod being upgraded to 2.7.4 kills other not-upgraded-yet pods with a newly added message type `PendingRequests`.   Interesting, according to the code, NATS carefully handles the situation that a cluster is consist of nodes in different versions.   It [checks peer's version](https://github.com/nats-io/nats-server/commit/d962500827ad36961c744fc02bba049c0205c2c0#diff-c6e9a3ce0d55948f2e7ea75a4de309986654f2ab11e0f8750625b88b28bd9ebfR1563) before sending out messages may be incompatible.  It assumes that peer would be soon upgraded to new version and then it could understand the new message.

**Comment by derekcollison** [comment]
Latest server release is 2.8.4.

**Comment by mugioka** [comment]
I was upgrade nats version from 2.8.2 to 2.8.4, downtime is occurred during 5min.
NATS log is bellow:

```
[nats-1 nats] [7] 2022/06/15 16:03:05.149963 [ERR] JetStream failed to store a msg on stream 'ADKTKO2PZJ5J2XSDTEZXHLOF6DLQVWPRAAXA5SY3EP7ACRXDGK6KKMFG > HOGE': expected sequence does not match store 
[nats-0 nats] [9] 2022/06/15 16:04:05.164590 [INF] JetStream cluster new stream leader for 'ADKTKO2PZJ5J2XSDTEZXHLOF6DLQVWPRAAXA5SY3EP7ACRXDGK6KKMFG > HOGE' 
[nats-1 nats] [7] 2022/06/15 16:04:05.153333 [WRN] Error applying entries to 'ADKTKO2PZJ5J2XSDTEZXHLOF6DLQVWPRAAXA5SY3EP7ACRXDGK6KKMFG > HOGE': last sequence mismatch 
[nats-1 nats] [7] 2022/06/15 16:04:05.188851 [WRN] Resetting stream cluster state for 'ADKTKO2PZJ5J2XSDTEZXHLOF6DLQVWPRAAXA5SY3EP7ACRXDGK6KKMFG > HOGE' 
[nats-0 nats] [9] 2022/06/15 16:04:06.224973 [WRN] Error loading message for catchup 'ADKTKO2PZJ5J2XSDTEZXHLOF6DLQVWPRAAXA5SY3EP7ACRXDGK6KKMFG > HOGE': malformed or corrupt message 
[nats-2 nats] [7] 2022/06/15 16:04:09.543781 [INF] JetStream cluster new consumer leader for 'ADKTKO2PZJ5J2XSDTEZXHLOF6DLQVWPRAAXA5SY3EP7ACRXDGK6KKMFG > HOGE > FUGA' 
[nats-1 nats] [7] 2022/06/15 16:04:09.716224 [INF] JetStream cluster new consumer leader for 'ADKTKO2PZJ5J2XSDTEZXHLOF6DLQVWPRAAXA5SY3EP7ACRXDGK6KKMFG > HOGE > FOO' 
[nats-1 nats] [7] 2022/06/15 16:04:16.167494 [WRN] Catchup for stream 'ADKTKO2PZJ5J2XSDTEZXHLOF6DLQVWPRAAXA5SY3EP7ACRXDGK6KKMFG > HOGE' stalled 
[nats-0 nats] [9] 2022/06/15 16:04:16.167943 [WRN] Error loading message for catchup 'ADKTKO2PZJ5J2XSDTEZXHLOF6DLQVWPRAAXA5SY3EP7ACRXDGK6KKMFG > HOGE': stream store EOF 
[nats-0 nats] [9] 2022/06/15 16:04:26.168326 [WRN] Error loading message for catchup 'ADKTKO2PZJ5J2XSDTEZXHLOF6DLQVWPRAAXA5SY3EP7ACRXDGK6KKMFG > HOGE': stream store EOF 
[nats-1 nats] [7] 2022/06/15 16:04:26.167825 [WRN] Catchup for stream 'ADKTKO2PZJ5J2XSDTEZXHLOF6DLQVWPRAAXA5SY3EP7ACRXDGK6KKMFG > HOGE' stalled 
[nats-1 nats] [7] 2022/06/15 16:04:36.168886 [WRN] Catchup for stream 'ADKTKO2PZJ5J2XSDTEZXHLOF6DLQVWPRAAXA5SY3EP7ACRXDGK6KKMFG > HOGE' stalled 
[nats-0 nats] [9] 2022/06/15 16:04:36.170278 [WRN] Error loading message for catchup 'ADKTKO2PZJ5J2XSDTEZXHLOF6DLQVWPRAAXA5SY3EP7ACRXDGK6KKMFG > HOGE': stream store EOF 
[nats-1 nats] [7] 2022/06/15 16:04:46.168983 [WRN] Catchup for stream 'ADKTKO2PZJ5J2XSDTEZXHLOF6DLQVWPRAAXA5SY3EP7ACRXDGK6KKMFG > HOGE' stalled 
[nats-0 nats] [9] 2022/06/15 16:04:46.169485 [WRN] Error loading message for catchup 'ADKTKO2PZJ5J2XSDTEZXHLOF6DLQVWPRAAXA5SY3EP7ACRXDGK6KKMFG > HOGE': stream store EOF 
[nats-1 nats] [7] 2022/06/15 16:04:56.169085 [WRN] Catchup for stream 'ADKTKO2PZJ5J2XSDTEZXHLOF6DLQVWPRAAXA5SY3EP7ACRXDGK6KKMFG > HOGE' stalled 
[nats-0 nats] [9] 2022/06/15 16:04:56.169566 [WRN] Error loading message for catchup 'ADKTKO2PZJ5J2XSDTEZXHLOF6DLQVWPRAAXA5SY3EP7ACRXDGK6KKMFG > HOGE': stream store EOF 
[nats-0 nats] [9] 2022/06/15 16:05:05.155487 [ERR] JetStream failed to store a msg on stream 'ADKTKO2PZJ5J2XSDTEZXHLOF6DLQVWPRAAXA5SY3EP7ACRXDGK6KKMFG > HOGE': expected sequence does not match store 
[nats-0 nats] [9] 2022/06/15 16:05:06.169968 [WRN] Error loading message for catchup 'ADKTKO2PZJ5J2XSDTEZXHLOF6DLQVWPRAAXA5SY3EP7ACRXDGK6KKMFG > HOGE': stream store EOF 
[nats-1 nats] [7] 2022/06/15 16:05:06.169579 [WRN] Catchup for stream 'ADKTKO2PZJ5J2XSDTEZXHLOF6DLQVWPRAAXA5SY3EP7ACRXDGK6KKMFG > HOGE' stalled 
[nats-1 nats] [7] 2022/06/15 16:05:16.170553 [WRN] Catchup for stream 'ADKTKO2PZJ5J2XSDTEZXHLOF6DLQVWPRAAXA5SY3EP7ACRXDGK6KKMFG > HOGE' stalled 
[nats-0 nats] [9] 2022/06/15 16:05:16.171853 [WRN] Error loading message for catchup 'ADKTKO2PZJ5J2XSDTEZXHLOF6DLQVWPRAAXA5SY3EP7ACRXDGK6KKMFG > HOGE': stream store EOF 
[nats-1 nats] [7] 2022/06/15 16:05:26.172215 [WRN] Catchup for stream 'ADKTKO2PZJ5J2XSDTEZXHLOF6DLQVWPRAAXA5SY3EP7ACRXDGK6KKMFG > HOGE' stalled 
[nats-0 nats] [9] 2022/06/15 16:05:26.174616 [WRN] Error loading message for catchup 'ADKTKO2PZJ5J2XSDTEZXHLOF6DLQVWPRAAXA5SY3EP7ACRXDGK6KKMFG > HOGE': stream store EOF 
[nats-1 nats] [7] 2022/06/15 16:05:36.172942 [WRN] Catchup for stream 'ADKTKO2PZJ5J2XSDTEZXHLOF6DLQVWPRAAXA5SY3EP7ACRXDGK6KKMFG > HOGE' stalled 
[nats-0 nats] [9] 2022/06/15 16:05:36.174129 [WRN] Error loading message for catchup 'ADKTKO2PZJ5J2XSDTEZXHLOF6DLQVWPRAAXA5SY3EP7ACRXDGK6KKMFG > HOGE': stream store EOF 
[nats-0 nats] [9] 2022/06/15 16:05:46.174158 [WRN] Error loading message for catchup 'ADKTKO2PZJ5J2XSDTEZXHLOF6DLQVWPRAAXA5SY3EP7ACRXDGK6KKMFG > HOGE': stream store EOF 
[nats-1 nats] [7] 2022/06/15 16:05:46.173607 [WRN] Catchup for stream 'ADKTKO2PZJ5J2XSDTEZXHLOF6DLQVWPRAAXA5SY3EP7ACRXDGK6KKMFG > HOGE' stalled 
[nats-1 nats] [7] 2022/06/15 16:05:56.173945 [WRN] Catchup for stream 'ADKTKO2PZJ5J2XSDTEZXHLOF6DLQVWPRAAXA5SY3EP7ACRXDGK6KKMFG > HOGE' stalled 
[nats-0 nats] [9] 2022/06/15 16:05:56.174407 [WRN] Error loading message for catchup 'ADKTKO2PZJ5J2XSDTEZXHLOF6DLQVWPRAAXA5SY3EP7ACRXDGK6KKMFG > HOGE': stream store EOF 
[nats-0 nats] [9] 2022/06/15 16:06:05.158048 [WRN] Error applying entries to 'ADKTKO2PZJ5J2XSDTEZXHLOF6DLQVWPRAAXA5SY3EP7ACRXDGK6KKMFG > HOGE': last sequence mismatch 
[nats-0 nats] [9] 2022/06/15 16:06:05.166286 [WRN] Resetting stream cluster state for 'ADKTKO2PZJ5J2XSDTEZXHLOF6DLQVWPRAAXA5SY3EP7ACRXDGK6KKMFG > HOGE' 
[nats-1 nats] [7] 2022/06/15 16:06:06.174356 [WRN] Catchup for stream 'ADKTKO2PZJ5J2XSDTEZXHLOF6DLQVWPRAAXA5SY3EP7ACRXDGK6KKMFG > HOGE' stalled 
[nats-1 nats] [7] 2022/06/15 16:06:16.174900 [WRN] Catchup for stream 'ADKTKO2PZJ5J2XSDTEZXHLOF6DLQVWPRAAXA5SY3EP7ACRXDGK6KKMFG > HOGE' stalled 
[nats-2 nats] [7] 2022/06/15 16:06:17.044857 [INF] JetStream cluster new stream leader for 'ADKTKO2PZJ5J2XSDTEZXHLOF6DLQVWPRAAXA5SY3EP7ACRXDGK6KKMFG > HOGE' 
[nats-2 nats] [7] 2022/06/15 16:06:17.048759 [INF] Catchup for stream 'ADKTKO2PZJ5J2XSDTEZXHLOF6DLQVWPRAAXA5SY3EP7ACRXDGK6KKMFG > HOGE' complete
```

I install nats with helm, values.yaml is bellow:
```
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - podAffinityTerm:
        labelSelector:
          matchLabels:
            app.kubernetes.io/instance: nats
            app.kubernetes.io/name: nats
        topologyKey: topology.kubernetes.io/zone
      weight: 100
    - podAffinityTerm:
        labelSelector:
          matchLabels:
            app.kubernetes.io/instance: nats
            app.kubernetes.io/name: nats
        topologyKey: kubernetes.io/hostname
      weight: 1
auth:
  enabled: true
  resolver:
    allowDelete: true
    interval: 1m
    operator: foo
    resolverPreload:
      AASU727EDXEETDBIV4GLBLAHR75RIDPGSTDO5WYKHBJRM6G2U2V3BWWR: bar
    store:
      dir: /accounts/jwt
      size: 1Gi
    systemAccount: fuga
    type: full
cluster:
  enabled: true
  noAdvertise: true
  replicas: 3
nats:
  image: nats:2.8.4-alpine
  jetstream:
    domain: hoge
    enabled: true
    encryption:
      key: hogehoge
    fileStorage:
      accessModes:
      - ReadWriteOnce
      enabled: true
      size: 10Gi
      storageDirectory: /data
    memStorage:
      enabled: false
podDisruptionBudget:
  maxUnavailable: 0
  minAvailable: 2
websocket:
  enabled: true
  noTLS: true
  port: 8080
```
