### ISSUE TITLE
account permission doesn't get updated in stream entity

### ISSUE THREAD

**Issue by alirezaDavid** [nats-io/nats-server#2969]
## Defect
Hi
We're facing an issue and unsure if it's a bug or happens by design.
The issue occurs when we create two accounts and set proper permission to publish to a subject in `account_a` and read from that subject in account_b(via stream), then create the corresponding ***stream*** based on the subject.

nats account config:
```
 accounts:
      account_a:
        users:
          - user: user_a
            password: **********
        jetstream: enabled
        exports:
          - stream: news.>
        
      account_b:
        users:
          - user: user_b
            password: **********
        jetstream: enabled
        imports:
           - stream:
               subject: news.>
               account: account_a
```
Stream configuration in `account_b`:

```
nats --user user_b --password ********** s create s_news

Configuration:

             Subjects: news.*
     Acknowledgements: true
            Retention: File - Limits
             Replicas: 1
       Discard Policy: Old
     Duplicate Window: 2m0s
    Allows Msg Delete: true
         Allows Purge: true
       Allows Rollups: false
     Maximum Messages: unlimited
        Maximum Bytes: unlimited
          Maximum Age: unlimited
 Maximum Message Size: unlimited
    Maximum Consumers: unlimited


Cluster Information:

                 Name: nats
               Leader: nats-js-0
```

 Now we can publish to the `news.articles` subject from account_a:
 
```
nats pub --user user_a --password ******** news.articles --count 200 "Message {{Count}} @ {{Time}}"
```

From account_b, if we check the number of messages in the stream, we can see that stream contains 200 messages.

```
nats --user user_b --password ********** info s  s_news
State:

            Messages: 200
            Bytes: 24 KiB
            FirstSeq: 1 
            LastSeq: 200
            Active Consumers: 1
```

So the communication (permission) is working as expected.
Now, without changing anything, let's update the permission like below:

```
 accounts:
      account_a:
        users:
          - user: user_a
            password: **********
        jetstream: enabled
   
        
      account_b:
        users:
          - user: user_b
            password: **********
        jetstream: enabled

```
We removed all the permissions for both accounts and restarted the server with the new configuration.

This is the moment that odd behavior happens; let's publish some messages to `news.articles` from account_a (exact scenario as before):

```
nats pub --user user_a --password ******** news.articles --count 200 "Message {{Count}} @ {{Time}}"
```

From account_b check the number of messages in the stream:
```
nats --user user_b --password ********** info s  s_news
State:

            Messages: 400
            Bytes: 50 KiB
            FirstSeq: 1 
            LastSeq: 400
            Active Consumers: 1
```

We expect to see 200 messages and not 400 because we removed the permission.
But if we create a new stream in account_b like below:

```
nats --user user_b --password ********** s create s_news_without_permission

Configuration:

             Subjects: news.*
     Acknowledgements: true
            Retention: File - Limits
             Replicas: 1
       Discard Policy: Old
     Duplicate Window: 2m0s
    Allows Msg Delete: true
         Allows Purge: true
       Allows Rollups: false
     Maximum Messages: unlimited
        Maximum Bytes: unlimited
          Maximum Age: unlimited
 Maximum Message Size: unlimited
    Maximum Consumers: unlimited


Cluster Information:

                 Name: nats
               Leader: nats-js-0
```

and publish some messages within account_a:
```
nats pub --user user_a --password ******** news.articles --count 200 "Message {{Count}} @ {{Time}}"
```

it seems that the new restrictions applied to this new stream(the number of messages is 0):

```
nats --user user_b --password ********** info s  s_news_without_permission
State:

            Messages: 0
            Bytes: 0
            FirstSeq: 0
            LastSeq: 0
            Active Consumers: 0
```

What about the old stream? Let's see the number of messages for the old stream(s_news):
```
nats --user user_b --password ********** info s  s_news
State:

            Messages: 600
            Bytes: 70 KiB
            FirstSeq: 1 
            LastSeq: 600
            Active Consumers: 1
```

The account permission doesn't get updated in stream entity when the new permission applies in the nats configuration.(but if we create a new stream, then the restrictions are there)

Is this expected?

Thanks in advance.
