### ISSUE TITLE
'context deadline exceeded' during jetstream.StreamInfo

### ISSUE THREAD

**Issue by sloev** [nats-io/nats-server#2990]
## context deadline exceeded during jetstream.StreamInfo

i am trying to connect to a nats server with jetstream enabled and get a jetstream info

it works locally with an in memory nats client but when i try using tls and a nats server in k8s it fails with an error i can find anywhere: 'context deadline exceeded' 

#### Versions of `nats-server` and affected client libraries used:
```
nats-server:  nats:2.7.4-alpine3.15
nats.go: github.com/nats-io/nats.go v1.13.1-0.20220308171302-2f2f6968e98d
```

#### OS/Container environment:
nats.conf: 
```
pid_file: "/var/run/nats/nats.pid"


http_port: 8222

listen: 0.0.0.0:4222

debug: $DEBUG
# trace=true 

server_name: $NATS_SERVER_NAME

cluster {
    name: C1

    port: 6222
    
    routes: [
        "nats://nats-0.nats.default.svc:6222",
        "nats://nats-1.nats.default.svc:6222",
        "nats://nats-2.nats.default.svc:6222"
    ]

    cluster_advertise: $CLUSTER_ADVERTISE
    
    connect_retries: 30
    
    no_advertise: true
}

leafnodes {
    port: 7422
}

tls: {
    cert_file: "/etc/nats-certs/tls.crt",
    key_file: "/etc/nats-certs/tls.key",
    ca_file: "/etc/nats-certs/tls.ca"
}  

include ./auth.conf
```

kubernetes yaml:
```
 containers:
      - name: nats
        image: nats:2.7.4-alpine3.15
        ports:
        - containerPort: 4222
          name: client
          hostPort: 4222
        - containerPort: 7422
          name: leafnodes
          hostPort: 7422
        - containerPort: 6222
          name: cluster
        - containerPort: 8222
          name: monitor
        - containerPort: 7777
          name: metrics

        command:
         - "nats-server"
         - "--jetstream"
         - "--config"
         - "/etc/nats-config/nats.conf"

        # Required to be able to define an environment variable
        # that refers to other environment variables.  This env var
        # is later used as part of the configuration file.
        env:
        - name: DEBUG
          value: "true"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: CLUSTER_ADVERTISE
          value: $(POD_NAME).nats.default.svc
        - name: NATS_SERVER_NAME
          value: N$(POD_NAME)-C1

        volumeMounts:
        - name: config-volume
          mountPath: /etc/nats-config
        - name: pid
          mountPath: /var/run/nats
        - name: nats-certs
          mountPath: /etc/nats-certs
          readOnly: true

        livenessProbe:
          httpGet:
            path: /
            port: 8222
          initialDelaySeconds: 10
          timeoutSeconds: 5

        readinessProbe:
          httpGet:
            path: /
            port: 8222
          initialDelaySeconds: 10
          timeoutSeconds: 5

        # Gracefully stop NATS Server on pod deletion or image upgrade.
        #
        lifecycle:
          preStop:
            exec:
              # Using the alpine based NATS image, we add an extra sleep that is
              # the same amount as the terminationGracePeriodSeconds to allow
              # the NATS Server to gracefully terminate the client connections.
              #
              command: ["/bin/sh", "-c", "/nats-server -DV -sl=ldm=/var/run/nats/nats.pid && /bin/sleep 60"]

```

#### Steps or code to reproduce the issue:
```
nc, err := nats.Connect(
  fmt.Sprintf("nats://%s:%d", conf.NatsHost, conf.NatsPort),
  nats.RootCAs(conf.TLSCaPath),
  nats.Secure(&tls.Config{InsecureSkipVerify: true}),
  nats.ClientCert(conf.TLSCertPath, conf.TLSKeyPath),
  nats.Nkey(string(pub), signingCb),
  nats.NoEcho(),
 )
if err != nil {
return nil, nil, fmt.Errorf("got err during nats.Connect(): %+v", err)
}

js, err := nc.JetStream()
if err != nil {
return nil, nil, fmt.Errorf("got err during nc.JetStream(): %+v", err)
}

err = setupJetStreams(js, conf.Slug)
stream, err := jsCtx.StreamInfo("foo")
```

#### Expected result:

being able to connect to nats and use jetstream to get stream info

#### Actual result:

log output during jsCtx.StreamInfo:
``
2022/04/01 13:24:42 got error during jsCtx.StreamInfo(streamName), err:context deadline exceeded
2022/04/01 13:24:42 creating jetstream "vessel_data_test-20" and subjects vessel.test-20.data.>
Error: got err during setupJetStreams: context deadline exceeded
``` 

nats-server log:
```
[17] 2022/04/01 11:24:37.589782 [DBG] 193.89.98.246:65450 - cid:16 - Client connection created
[17] 2022/04/01 11:24:37.589874 [DBG] 193.89.98.246:65450 - cid:16 - Starting TLS client connection handshake
[17] 2022/04/01 11:24:37.647743 [DBG] 193.89.98.246:65450 - cid:16 - TLS handshake complete
[17] 2022/04/01 11:24:37.647844 [DBG] 193.89.98.246:65450 - cid:16 - TLS version 1.3, cipher suite TLS_AES_128_GCM_SHA256
[17] 2022/04/01 11:24:39.983876 [DBG] 193.89.98.246:65450 - cid:16 - "v1.13.0:go" - Client Ping Timer
[17] 2022/04/01 11:24:47.688342 [DBG] 193.89.98.246:65450 - cid:16 - "v1.13.0:go" - Client connection closed: Client Closed
```
