### ISSUE TITLE
2.7.4 Jetstream Server Crashing with `Router connection closed: Read Error`

### ISSUE THREAD

**Issue by Kampe** [nats-io/nats-server#3063]
Hello!

We're running the latest build and are utilizing jetstream and leaf node topology and are seeing issue crop up with nats over time.

```

  |   | [328] 2022/04/20 23:28:28.952337 [INF] Starting nats-server
  |   | [328] 2022/04/20 23:28:28.952368 [INF]   Version:  2.7.4
```
```
  |   | [328] 2022/04/20 23:28:28.953868 [INF] Starting JetStream cluster
  |   | [328] 2022/04/20 23:28:28.953870 [INF] Creating JetStream metadata controller
  |   | [328] 2022/04/20 23:28:28.954521 [INF] JetStream cluster recovering state
  |   | [328] 2022/04/20 23:28:28.957244 [INF] Listening for client connections on 0.0.0.0:4222
  |   | [328] 2022/04/20 23:28:28.957428 [INF] Server is ready
  |   | [328] 2022/04/20 23:28:28.958572 [INF] Cluster name is pf-0008-03
  |   | [328] 2022/04/20 23:28:28.959065 [INF] Listening for route connections on 0.0.0.0:6222
  |   | [328] 2022/04/20 23:28:28.961478 [INF] 10.42.0.246:6222 - rid:6 - Route connection created
  |   | [328] 2022/04/20 23:28:28.962928 [INF] 10.43.160.36:7422 - lid:7 - Leafnode connection created for account: $G
  |   | [328] 2022/04/20 23:28:28.963480 [INF] 10.42.0.244:6222 - rid:8 - Route connection created
  |   | [328] 2022/04/20 23:28:29.413404 [INF] JetStream cluster new metadata leader: nats-edge-2/pf-0008-03
  |   | [328] 2022/04/20 23:28:29.529414 [INF] 10.42.0.244:6222 - rid:8 - Router connection closed: Read Error
  |   | [328] 2022/04/20 23:28:29.675223 [INF] 10.42.0.244:59022 - rid:10 - Route connection created
  |   | [328] 2022/04/20 23:28:29.906158 [INF] Self is new JetStream cluster metadata leader
  |   | [328] 2022/04/20 23:28:29.916065 [INF] 10.42.0.246:57076 - rid:12 - Route connection created
  |   | [328] 2022/04/20 23:28:29.916211 [INF] 10.42.0.246:57076 - rid:12 - Router connection closed: Duplicate Route
  |   | [328] 2022/04/20 23:28:30.212475 [INF] 10.43.160.36:7422 - lid:7 - Adding deny [$JS.API.> $KV.> $OBJ.>] for account "$G"
  |   | [328] 2022/04/20 23:28:30.609393 [INF] 10.42.0.244:6222 - rid:15 - Route connection created
  |   | [328] 2022/04/20 23:28:30.609508 [INF] 10.42.0.244:6222 - rid:15 - Router connection closed: Duplicate Route
```

nats will be running normally, and then become unstable and crash loop like we see here.  This has a rolling effect on all of the nats statefulset.

Here's our configuration:

```
  nats.conf: |
    pid_file: "/var/run/nats/nats.pid"
    http: 8222
    server_name: $POD_NAME

    cluster {
      name: $CLUSTER_ID
      port: 6222

      # Use explicit static routes to avoid intermittent DNS issues
      # that could cause partitions via gossip while bootstrapping.
      routes [
        nats://nats-edge-0.nats-edge.default.svc:6222
        nats://nats-edge-1.nats-edge.default.svc:6222
        nats://nats-edge-2.nats-edge.default.svc:6222
      ]

      cluster_advertise: $CLUSTER_ADVERTISE
      connect_retries: 60
    }

    leafnodes {
      remotes [
        {
          url: "nats://$LEAFNODE_TOKEN@nats-cloud-gateway.default.svc:7422"
        }
      ]
    }
    
    jetstream {
      store_dir: /data/jetstream/store
      max_mem: 1G
      max_file: 2G
    }

```

**Comment by Kampe** [comment]
Nothing in terms of OOM, here's the event log though, it seems to not respond to healthchecks:

```
57m         Warning   Unhealthy          pod/nats-edge-0                                            Readiness probe failed: Get "http://10.42.0.247:8222/": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
12m         Warning   Unhealthy          pod/nats-edge-0                                            Liveness probe failed: Get "http://10.42.0.247:8222/": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2m28s       Warning   BackOff            pod/nats-edge-0                                            Back-off restarting failed container
32m         Normal    Pulled             pod/nats-edge-1                                            Container image "nats:2.7.4" already present on machine
12m         Warning   Unhealthy          pod/nats-edge-1                                            Liveness probe failed: Get "http://10.42.0.246:8222/": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2m22s       Warning   BackOff            pod/nats-edge-1                                            Back-off restarting failed container
12m         Warning   Unhealthy          pod/nats-edge-2                                            Liveness probe failed: Get "http://10.42.0.244:8222/": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
37m         Warning   Unhealthy          pod/nats-edge-2                                            Readiness probe failed: Get "http://10.42.0.244:8222/": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2m21s       Warning   BackOff            pod/nats-edge-2                                            Back-off restarting failed container
```

**Comment by Kampe** [comment]
Here's how we deploy nats:
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nats
  labels:
    app: nats
spec:
  selector:
    matchLabels:
      app: nats
  replicas: 3
  serviceName: "nats"
  template:
    metadata:
      labels:
        app: nats
    spec:
      # Common volumes for the containers
      volumes:
      - name: config-volume
        configMap:
          name: nats-config
      - name: pid
        emptyDir: {}

      shareProcessNamespace: true
      serviceAccountName: nats-server
      terminationGracePeriodSeconds: 60
      containers:
      #  NATS Server  #
      - name: nats
        image: nats:2.8.0
        ports:
        - containerPort: 4222
          name: client
        - containerPort: 7422
          name: leafnodes
        - containerPort: 6222
          name: cluster
        - containerPort: 8222
          name: monitor
        - containerPort: 7777
          name: metrics
        command:
         - "/nats-server"
         - "--config"
         - "/etc/nats-config/nats.conf"
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CLUSTER_ADVERTISE
          value: '$(POD_NAME).nats.$(POD_NAMESPACE).svc'
        - name: LEAFNODE_TOKEN
          valueFrom:
            secretKeyRef:
              name: nats-creds
              key: token
        volumeMounts:
          - name: config-volume
            mountPath: /etc/nats-config
          - name: pid
            mountPath: /var/run/nats
          - name: nats-js-sts-vol
            mountPath: /data/jetstream
        # Disable all cpu limits for the server.
        resources:
          requests:
            cpu: 0
        # Liveness/Readiness probes against the monitoring container
        livenessProbe:
          httpGet:
            path: /
            port: 8222
          initialDelaySeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 8222
          initialDelaySeconds: 10
          timeoutSeconds: 5
        # Gracefully stop NATS Server on pod deletion or image upgrade.
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "/nats-server -sl=ldm=/var/run/nats/nats.pid && /bin/sleep 60"]

      #  NATS Configuration Reloader  #        
      - name: reloader
        image: wallyqs/nats-server-config-reloader:fclose
        command:
         - "nats-server-config-reloader"
         - "-pid"
         - "/var/run/nats/nats.pid"
         - "-config"
         - "/etc/nats-config/nats.conf"
        volumeMounts:
          - name: config-volume
            mountPath: /etc/nats-config
          - name: pid
            mountPath: /var/run/nats

      #  NATS Prometheus Exporter  #
      - name: metrics
        image: natsio/prometheus-nats-exporter:0.9.1
        args:
        - -connz
        - -routez
        - -serverz
        - -subz
        - -gatewayz
        - -varz
        - -channelz
        - -prefix=nats
        - -use_internal_server_id
        - -DV
        - http://localhost:8222
        ports:
        - containerPort: 7777
          name: metrics
  volumeClaimTemplates:
  - metadata:
      name: nats-js-sts-vol
    spec:
      accessModes:
        - ReadWriteOnce
      volumeMode: 'Filesystem'
      resources:
        requests:
          storage: 2Gi
```

We recently enabled jetstream and that's when we started noticing a lot of these issues
