### ISSUE TITLE
JetStream resource limits exceeded for server

### ISSUE THREAD

**Issue by aopetrov86** [nats-io/nats-server#3672]
## Defect

Make sure that these boxes are checked before submitting your issue -- thank you!

 - [ ] Included `nats-server -DV` output
 - [ ] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

#### Versions of `nats-server` and affected client libraries used:
nats-server: v2.9.6

#### OS/Container environment:
nats:2.9.6-alpine3.16 docker image
#### Expected result:
Server works

#### Actual result:
Server error `JetStream resource limits exceeded for server`
with 
```
$ du -s /data
2302156 /data
```
and jetstream.fileStorage.size: 20Gi
prometheus nats_varz_jetstream_stats_storage metric show 22_110_019_054 B

**Comment by ripienaar** [comment]
Please she your configs and account settings.

**Comment by aopetrov86** [comment]
@ripienaar 
values.yaml:
```yaml
nats:
  cluster:
    enabled: true
    replicas: 3
  
  publish:
    maxpending: 60000
  
  nats:
    image: "nats:2.9.6-alpine3.16"
    jetstream:
      enabled: true
      
      memStorage:
        enabled: true
        size: 2Gi
      
      fileStorage:
        enabled: true
        storageDirectory: /data
        size: 20Gi
        storageClassName: "local-path"
        accessModes:
          - ReadWriteOnce
  natsbox:
    enabled: false
  
  exporter:
    image: "natsio/prometheus-nats-exporter:0.10.0"
    serviceMonitor:
      enabled: true
      namespace: monitoring
      labels:
        release: prom

  reloader:
    enabled: false

  useFQDN: false
  statefulSetPodLabels:
    app.kubernetes.io/component: "nats"
  
  podDisruptionBudget:
    enabled: false
  
  securityContext:
    fsGroup: 1000
    runAsUser: 1000
    runAsNonRoot: true
```
