### ISSUE TITLE
Adding a SYS user hides any existing streams

### ISSUE THREAD

**Issue by raypinto** [nats-io/nats-server#3722]
## Defect

Make sure that these boxes are checked before submitting your issue -- thank you!

 - [ ] Included `nats-server -DV` output
 - [ ] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

#### Versions of `nats-server` and affected client libraries used:
2.9.9

#### OS/Container environment:
Docker

#### Steps or code to reproduce the issue:

- Create the following config file:

conf.yaml
```
nats:
  image: nats:alpine

  jetstream:
    enabled: true

    fileStorage:
      enabled: true
      size: "1Gi"
      storageDirectory: /data/

cluster:
  enabled: true
  replicas: 3
```

- Install nats using latest helm charts using the command: 
  - `helm install nats nats/nats --values conf.yaml`

- Create a stream using the nats cli

- Create the following config file with basic auth:

config_new.yaml
```
nats:
  image: nats:alpine

  jetstream:
    enabled: true

    fileStorage:
      enabled: true
      size: "1Gi"
      storageDirectory: /data/

cluster:
  enabled: true
  replicas: 3

auth:
  enabled: true
  systemAccount: SYS
  basic:
    noAuthUser: user
    accounts:
      SYS:
        users:
        - user: sys
          password: sys
      \$G:
        users:
        - user: user
          password: user
        jetstream: true
```

- Upgrade nats using latest helm charts using the command: 
  - `helm upgrade nats nats/nats --values conf_new.yaml`

- Check the stream created before the upgrade. The stream does not show up when running: `nats stream ls`

#### Expected result:

The config reloader reloads the new auth config without restarting the nats servers. The stream is still present and can be used. 

#### Actual result:

The nats servers are restarted. The stream is not visible and  also any consumers that created earlier (if any) are not retrievable.

**Comment by wallyqs** [comment]
Thanks for the report @raypinto, taking a look

**Comment by wallyqs** [comment]
What is happening here is that configuration reload does not work for neither `NoAuthUser` nor `SystemAccount`:

```
Failed to reload server configuration: config reload not supported for NoAuthUser: old=, new=user
```

Then there are other extra couple of issues in the config:

```yaml
accounts: 
  $G:
        users:
        - user: user
          password: user
```

The default $G account where the original stream assets cannot be configured under the `accounts` block since it will throw a Reserved Account error.

So the way to set this up would be something like:

```hcl
    ##################
    #                #
    # Authorization  #
    #                #
    ##################
    system_account: "$SYS"
    no_auth_user: user
    authorization {
      users: [
        {"password":"user","user":"user"},
      ]
    }

    accounts:{"$SYS":{"users":[{"password":"sys","user":"sys"}]}}
```
The `nats.configChecksumAnnotation` (enabled by default) will instead cause the restart as a workaround of no auth user and system account not being supported via config reload.
Moving this issue to `nats-io/k8s` to be able to support this type of configuration.
