### ISSUE TITLE
Creating consumer without/wrong durable name fails

### ISSUE THREAD

**Issue by siredmar** [nats-io/nats-server#3821]
## Defect

Using the the nats cli AND the nats go sdk both seem to no give an error when a consumer is created if
- the `Durable` field is missing or
- the `Durable` field does not equal the `Name` field.

Instead some sort of zombie consumer is created but deleted after a very short time.

#### Versions of `nats-server` and affected client libraries used:
nats-server: 2.9.11
nats cli: 0.0.33
github.com/nats-io/nats.go v1.22.1

#### OS/Container environment:
k8s v1.25.3, nats:2.9.11-alpine

#### Steps or code to reproduce the issue:

Having this configuration file and creating the consumer will create the output

**Example: missing durable name**

```yaml
{
  "stream_name": "main-acc1",
  "name": "main-acc1-defect",
  "config": {
    "ack_policy": "explicit",
    "ack_wait": 30000000000,
    "deliver_policy": "all",
    "max_ack_pending": 1000,
    "max_deliver": -1,
    "max_waiting": 512,
    "replay_policy": "instant",
    "num_replicas": 0
  }
}
```

**Example: wrong durable name**

```yaml
{
  "stream_name": "main-acc1",
  "name": "main-acc1-foo",
  "config": {
    "durable_name": "foo",
    "ack_policy": "explicit",
    "ack_wait": 30000000000,
    "deliver_policy": "all",
    "max_ack_pending": 1000,
    "max_deliver": -1,
    "max_waiting": 512,
    "replay_policy": "instant",
    "num_replicas": 0
  }
}
```

```bash
$ nats consumer add -s nats://127.0.0.1:4222 --creds cluster/local/config/nsc/nsc/nkeys/creds/myoperator/acc1/user.creds --config /tmp/cons.json
? Select a Stream main-acc1
Information for Consumer main-acc1 > AMJXDAOO created 2023-01-26T13:56:46+01:00

Configuration:

           Pull Mode: true
      Deliver Policy: All
          Ack Policy: None
       Replay Policy: Instant
   Max Waiting Pulls: 512
  Inactive Threshold: 5.00s

State:

   Last Delivered Message: Consumer sequence: 0 Stream sequence: 0
     Unprocessed Messages: 0
            Waiting Pulls: 0 of maximum 512

# the consumer can be seen after creation
$ nats consumer list -s nats://127.0.0.1:4222 --creds cluster/local/config/nsc/nsc/nkeys/creds/myoperator/acc1/user.creds                       
? Select a Stream main-acc1
Consumers for Stream main-acc1:

	AMJXDAOO


# repeating this after 1 second shows that there are no consumers
$ nats consumer list -s nats://127.0.0.1:4222 --creds cluster/local/config/nsc/nsc/nkeys/creds/myoperator/acc1/user.creds
? Select a Stream main-acc1
No Consumers defined
```

So it seems the "unnamed" consumers get deleted. 
This also happens when using the nats go sdk
```golang
// CreateConsumer creates a new jetstream consumer with a given configuration for a given domain and stream
func (c *Client) CreateConsumer(domain string, stream string, config *nats.ConsumerConfig) error {
	jsOpts := []nats.JSOpt{}
	if domain != "" {
		jsOpts = append(jsOpts, nats.Domain(domain))
	}

	jsctx, err := c.conn.JetStream(jsOpts...)
	if err != nil {
		return err
	}

	_, err = jsctx.AddConsumer(stream, config)
	if err != nil {
		return err
	}

	return nil
}
```

#### Expected result:

I'd expect **either** setting any durable name i want or let it be auto generated if not specified **or** return an error if the durable name is not correct.

#### Actual result:

In any case mentioned above a consumer gets created without errors, but disappears after a few seconds.
