### ISSUE TITLE
After changing the replica of a stream: The non-leaders have more messages

### ISSUE THREAD

**Issue by stefanmeschke** [nats-io/nats-server#3848]
## Defect

Make sure that these boxes are checked before submitting your issue -- thank you!

 - [x] Included `nats-server -DV` output
```
[124] 2023/02/06 08:14:04.050458 [INF] Starting nats-server
[124] 2023/02/06 08:14:04.050483 [INF]   Version:  2.9.11
[124] 2023/02/06 08:14:04.050485 [INF]   Git:      [23ffc16]
[124] 2023/02/06 08:14:04.050491 [DBG]   Go build: go1.19.4
[124] 2023/02/06 08:14:04.050496 [INF]   Name:     NBS3DHEIAJA2NGY2ZQ6IL2MK4YLIDGIZNF3IKORWUNMVAQEJOGJHY3EZ
[124] 2023/02/06 08:14:04.050498 [INF]   ID:       NBS3DHEIAJA2NGY2ZQ6IL2MK4YLIDGIZNF3IKORWUNMVAQEJOGJHY3EZ
```
 - [x] Included a Minimal, Complete, and Verifiable example: Please see section _"Steps or code to reproduce the issue"_

#### Versions of `nats-server` and affected client libraries used:

Reproducible in different versions and setups.

#### OS/Container environment:

Reproducible for various operating systems and environments (k8s, locally mac, locally linux, …).

#### Steps or code to reproduce the issue:

<details>
  <summary><code>docker-compose.yml</code></summary>

  ```yml
  version: '3'
  services:
    nats-1:
      container_name: nats-1
      image: nats:2.9.11
      entrypoint: /nats-server
      command: --name nats-1 --cluster_name NATS --js --sd /data --cluster nats://0.0.0.0:4245 --routes nats://nats-1:4245,nats://nats-2:4245,nats://nats-3:4245 -p 4222 --http_port 8222
      networks:
        - nats
      ports:
        - 14222:4222
        - 18222:8222
  
    nats-2:
      container_name: nats-2
      image: nats:2.9.11
      entrypoint: /nats-server
      command: --name nats-2 --cluster_name NATS --js --sd /data --cluster nats://0.0.0.0:4245 --routes nats://nats-1:4245,nats://nats-2:4245,nats://nats-3:4245 -p 4222 --http_port 8222
      networks:
        - nats
      ports:
        - 24222:4222
        - 28222:8222
  
    nats-3:
      container_name: nats-3
      image: nats:2.9.11
      entrypoint: /nats-server
      command: --name nats-3 --cluster_name NATS --js --sd /data --cluster nats://0.0.0.0:4245 --routes nats://nats-1:4245,nats://nats-2:4245,nats://nats-3:4245 -p 4222 --http_port 8222
      networks:
        - nats
      ports:
        - 34222:4222
        - 38222:8222
  
    nats-setup:
      container_name: nats_setup
      depends_on:
        - nats-1
        - nats-2
        - nats-3
      build:
        context: .
      environment:
        - NATS_URL=nats://host.docker.internal:14222
      networks:
        - nats
  
  networks:
    nats: {}
  ```
</details>

<details>
  <summary><code>Dockerfile</code></summary>

  ```yml
  FROM alpine:3.17
  
  RUN apk add --no-cache wget rclone curl jq && \
      wget -P ~ https://github.com/nats-io/natscli/releases/download/v0.0.35/nats-0.0.35-linux-arm64.zip && \
      unzip -d ~ ~/nats-0.0.35-linux-arm64.zip && \
      cp ~/nats-0.0.35-linux-arm64/nats /usr/local/bin && \
      adduser -D user
  
  WORKDIR /workdir
  
  COPY stream.conf .
  COPY script.sh .
  RUN chmod +x script.sh
  
  USER user
  
  ENTRYPOINT ["/workdir/script.sh"]
  ```
</details>

<details>
  <summary><code>script.sh</code></summary>

  ```sh
  #!/bin/sh
  
  function fetch_stream_information() {
    N1=$(curl --silent "http://nats-1:8222/jsz?consumers=1" | jq ".messages")
    N2=$(curl --silent "http://nats-2:8222/jsz?consumers=1" | jq ".messages")
    N3=$(curl --silent "http://nats-3:8222/jsz?consumers=1" | jq ".messages")
  
    echo "=================="
    echo "nats-1: $N1"
    echo "nats-2: $N2"
    echo "nats-3: $N3"
    echo "=================="
  }
  
  nats stream ls
  nats stream create --config=stream.conf
  nats stream info test
  
  nats pub test.a --count 10 "Message {{Count}} @ {{Time}}"
  sleep 1
  nats pub test.a --count 10 "Message {{Count}} @ {{Time}}"
  sleep 1
  nats pub test.a --count 10 "Message {{Count}} @ {{Time}}"
  sleep 1
  nats pub test.a --count 10 "Message {{Count}} @ {{Time}}"
  sleep 1
  nats pub test.a --count 10 "Message {{Count}} @ {{Time}}"
  sleep 1
  
  fetch_stream_information
  
  nats stream edit --replicas=3 --force test
  
  sleep 2
  fetch_stream_information
  sleep 2
  fetch_stream_information
  sleep 2
  fetch_stream_information
  
  nats pub test.a --count 4 "Message {{Count}} @ {{Time}}"
  
  sleep 1
  fetch_stream_information
  sleep 1
  fetch_stream_information
  sleep 1
  fetch_stream_information
  sleep 1
  fetch_stream_information
  sleep 1
  fetch_stream_information
  ```
</details>

<details>
  <summary><code>stream.conf</code></summary>

  ```json
  {
    "config":{
      "name":"test",
      "subjects":[
        "test.*"
      ],
      "retention":"limits",
      "max_consumers":-1,
      "max_msgs":100,
      "max_bytes":-1,
      "max_age":10000000000,
      "max_msg_size":-1,
      "storage":"file",
      "discard":"old",
      "num_replicas":1,
      "duplicate_window":5000000000,
      "deny_delete":false,
      "deny_purge":false,
      "allow_rollup_hdrs":true
    },
    "created":"2021-02-27T23:49:36.700424Z",
    "state":{
      "messages":0,
      "bytes":0,
      "first_seq":0,
      "first_ts":"0001-01-01T00:00:00Z",
      "last_seq":0,
      "last_ts":"0001-01-01T00:00:00Z",
      "consumer_count":0
    }
  }
  ```
</details>

1. download all files
2. run `docker compose up --build --force-recreate --remove-orphans --renew-anon-volumes`
3. observe logs

Short explanation what this scenario does:

1. Creation of a stream with `replica: 1` and a time based retention
2. Publish 50 messages
3. Change stream configuration to `replica: 3`
4. Wait
5. Publish 4 messages
6. ⚠️ The replicas have more messages than the leader

#### Expected result:

After changing the replica size of a stream and the first retention of a message the messages on all replicas are the same.

#### Actual result:

After changing the replica size of a stream and the first retention of a message the messages on the leader are the correct ones, but the replicas have old messages.

**Thanks in advance! 🙏** 

Cheers
Stefan
