### ISSUE TITLE
JetStream takes >30min to restore Stream upgrading from `2.9.22` to `2.10.7`

### ISSUE THREAD

**Issue by vitorquintanilha** [nats-io/nats-server#4914]
### Observed behavior

I'm running a cluster with 3 nodes and JetStream enabled using [the official helm chart](https://github.com/nats-io/k8s/tree/main/helm/charts/nats). I'm trying to upgrade from version `2.9.22` to `2.10.7` (chart version `1.0.3` to `1.1.6`). I have a single Stream with 1 Replica and about 50Gb of size.

When performing the upgrade, the pods that do NOT contain the stream data are upgraded just fine.

However, when trying to upgrade the pod WITH the Stream data, I see this message being logged right after the usual startup messages:

```
[INF]   Starting restore for stream '$G > XXXXXXX'
```

After this message, a warning similar to this is logged every 10s:

```
[WRN] Healthcheck failed: "failed to be ready for connections after 1ms: server, route"
```

I have waited for over 30min for the Stream to be restored but it never ended. I ended up rolling back the upgrade since I couldn't support more downtime (and because I have only 1 Replica I was facing a downtime).

I have tried to upgrade to `2.9.15` and saw the same behavior.

The rollback works as expected. We see the same log messages as above, but after around 2~3min we see the restore was a success:

```
[INF]   Restored 23,329,511 messages for stream '$G > XXXXXX'
[INF]   Recovering 23 consumers for stream - '$G > XXXXXXX'
```

Stream info: https://paste.mozilla.org/ieNyxL21
Config file: https://paste.mozilla.org/a6ZBRRDn

### Expected behavior

I expect the startup of the node in versions `2.10.7` and `2.10.5` to take a similar time as in version `2.9.22` (e.g. around 2min).

### Server and client version

NATS `2.9.22` (upgrading to `2.10.7`)
NATS Helm Chart `1.0.3` (upgrading to `1.1.6`)

### Host environment

Running on k8s with partial helm config:

```
container:
    resources:
      requests:
        cpu: 2
        memory: 6Gi
      limits:
        cpu: 6
        memory: 18Gi

config:
  cluster:
    enabled: true
    replicas: 3
    
  jetstream:
    enabled: true
    memoryStore:
      enabled: true
      maxSize: 1Gi
    fileStore:
      enabled: true
      pvc:
        enabled: true
        size: 150Gi
```
