### ISSUE TITLE
JetStream Object Storage Fails When Overwritting

### ISSUE THREAD

**Issue by RaoXin2** [nats-io/nats-server#4951]
### Observed behavior

- Steps 1: Starts NATs service from this config file, and running it inside an docker image:

``` Yaml
# Client port of 4222 on all interfaces
port: 4222

# HTTP monitoring port
monitor_port: 8222

# configure for jetstream
jetstream {
  store_dir: /nats/storage
  max_memory_store: 70MB
  max_file_store: 10GB
}

#log options
debug:   true
trace:   true
logtime: true
log_file: "/nats-server.log"
```

- Step 2: Using golang to store 800 image files with size of 900kb each
``` Go
// connect to nats & jetstream
nc, err := nats.Connect("nats://127.0.0.1:4222")
if err != nil {
    defer nc.Close()
}
defer nc.Close()
js, _ := nc.JetStream()
_, _ = js.CreateObjectStore(&nats.ObjectStoreConfig{
    Bucket: "images",
})
kv, _ := js.ObjectStore("images")

// read files
file, err := fileheader.Open()
if err != nil {
    return err
}
bts := make([]byte, fileheader.Size)
_, err = bufio.NewReader(file).Read(bts)
if err != nil {
    return fiber.NewError(fiber.StatusBadRequest, "file saving failed"+err.Error())
}

// save 800 images
for i := 0; i < 100; i++ {
    for j := 0; j < 8; j++ {
        res, _ := kv.PutBytes(fmt.Sprintf("%s-%d-%d", p.Name, i, j), bts)
        print(res.Name, " saved!\n")
    }
    time.Sleep(10 * time.Millisecond)
}
```
- Step 3: Rewrite an object by storing an object in a same bucket with the same name
Docker container exits with code 137

### Expected behavior

Expected:
All three steps are success, and the object is being rewritten.

### Server and client version

NATs version: 2.10.3

### Host environment

System: Win11 10.0.22621
CPU: Intel(R) Core(TM) i7-10750H @2.6GHz
RAM: 64G

### Steps to reproduce

Refer to steps in "Observed behavior" section

**Comment by Jarema** [comment]
Thanks for filling the issue.

Error 137 means that the container tried to use more memory that it has access to.
I suppose it might be due to limits you have set in you docker setup.

What are those limits?

**Comment by RaoXin2** [comment]
Hi @Jarema Thanks for responding my message.

The only limit for container is that mem_limit is set to 200MB, and it works fine when storing 800 images with size of 900KB each.

The NATs container part in docker-compose.yaml
``` yaml
  nats:
    container_name: nats
    image: <link_to_image>/object-db:0.1.1
    networks:
      - proxy-redirect
    mem_limit: 200mb
```
