### ISSUE TITLE
Consumer's max_deliver setting does not remove message after given naks

### ISSUE THREAD

**Issue by lucassith** [nats-io/nats-server#4956]
### Observed behavior

In my case, `max_deliver = 3` and `max_ack_pending = -1` does not result in deleting messages when `metadata.redeliveryCount = 3` and I execute the `.nak(60000)` method again.

More information presented on a Nats' Slack thread.
https://natsio.slack.com/archives/CM3T6T7JQ/p1705066905106789

### Expected behavior

Once the `metadata.redeliveryCount` reaches 3 and I `.nak(60000)` the message again, it should be removed immidiatelly from the stream.

### Server and client version

server: Intially observed on 2.10.0, update to 2.10.9 didn't fix the problem.
application: 2.18.0 (NodeJS + npm)

### Host environment

jetstream enabled, 3 nats instances
docker-compose:

```
  nats:
    image: nats:2.10.9-alpine
    ports:
      - 8222:8222
      - 41222:4222
    restart: unless-stopped
    command: "--cluster_name NATS --jetstream --cluster nats://0.0.0.0:6222 -n=nats-main --http_port 8222  --routes=nats://nats:siemens@nats:6222"
    networks: ["nats"]
  nats-1:
    image: nats:2.10.9-alpine
    restart: unless-stopped
    ports:
      - 42222:4222
    command: "--cluster_name NATS --jetstream --cluster nats://0.0.0.0:6222 -n=nats-1 --routes=nats://nats:siemens@nats:6222"
    networks: ["nats"]
    depends_on: ["nats"]
  nats-2:
    image: nats:2.10.9-alpine
    ports:
      - 43222:4222
    restart: unless-stopped
    command: "--cluster_name NATS --jetstream --cluster nats://0.0.0.0:6222 -n=nats-2 --routes=nats://nats:siemens@nats:6222"
    networks: ["nats"]
    depends_on: ["nats"]
networks:
  nats:
    name: nats
```

### Steps to reproduce

I started the exchange with around 4mln of messages. (3Gb of data). Some messages were ack'ed and the count went down to 1.1 mln. These messages were supposed to be removed due to the business logic, once every single message was naked 3 times.
