### ISSUE TITLE
Inconsistent behavior for workqueue consumers

### ISSUE THREAD

**Issue by LautaroJayat** [nats-io/nats-server#4957]
### Observed behavior

**TLDR;**
When creating two suscribers with different names and non exclusive filtered subjects sometimes the servers responds with an error and prevents you to create the consumer, but other times it allows creations and prompt you to manually remove it.

**Given the following scenario:**
* One Nats Cluster with Jetstream enabled
* Just one Stream with the following subject: `testing.*`
* Subscriber with name `subscriber-a` suscribes to `testing.>` and everything goes OK.
* Subscriber with name `subscriber-b` tries to join to `testing.>` gets rejected **BUT**:

1. In one case we get this message in the nats console:  `[WRN] Proposing to delete consumer 'APP > suscriber-b > testing.1-v2' due to assignment response error: filtered consumer not unique on workqueue stream (10100)`. The Go client used receives an error and we can handle this easily in the application.

2. In other cases we get this message in the nats console: `[WRN] Consumer "subscriber-b" > "testing.1-v2" has a filter subject that overlaps with other consumers, which is not allowed for a stream with WorkQueue policy, it should be administratively deleted`. The Go client used does not error and the application has no way to know this happened.

### Expected behavior

The cluster should respond with a consistent answer when two subscribers with different names tries to join a stream but they have overlapping subject filters.
If possible, the response should be something like an error, so applications can understand what is happening.

### Server and client version

Client: `github.com/nats-io/nats.go v1.31.0` 

Server: official docker image `nats:latest`

### Host environment

```bash
uname -a
# Linux 6.2.0-39-generic #40~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC x86_64 GNU/Linux
```

### Steps to reproduce

1. Create a nats cluster with Jetstream enabled.
2. Create a stream.
4. Join one go client with the following steps: 

```go
// First client will connect with no problem
nc, _ := nats.Connect( /* nats url */ )
js,  _ := jetstream.New(nc)
consumer, err := js.CreateOrUpdateConsumer(context.TODO(), "testing", jetstream.ConsumerConfig{
	Name:           "testing-v1",
	FilterSubjects: []string{"testing.>"},
})

/***********************************************************************************/

// second client will fail but with no consistent response from server
nc, _ := nats.Connect( /* nats url */ )
js, _ := jetstream.New(nc)
consumer, err := js.CreateOrUpdateConsumer(context.TODO(), "testing", jetstream.ConsumerConfig{
	Name:           "testing-v2",
	FilterSubjects: []string{"testing.>"},
})
```

*Stream configuration*
```json
{
    "config": {
      "name": "testing",
      "subjects": [
        "testing.*"
      ],
      "retention": "workqueue",
      "max_consumers": -1,
      "max_msgs_per_subject": -1,
      "max_msgs": -1,
      "max_bytes": -1,
      "max_age": 0,
      "max_msg_size": -1,
      "storage": "memory",
      "discard": "new",
      "num_replicas": 1,
      "duplicate_window": 120000000000,
      "sealed": false,
      "deny_delete": false,
      "deny_purge": false,
      "allow_rollup_hdrs": false,
      "allow_direct": true,
      "mirror_direct": false
    }}
```

*Cluster configuration*

```conf
# ./testdata/jetstream.conf

jetstream {
    store_dir: /tmp/jetstream/
    max_mem: 1G
    max_file: 100G
}


accounts: {
  $SYS: {
    users: [{user: sys, password: pass}]
  }
  APP: {
    jetstream: true
    users: [{user: user, password: pass}]
  }
}


cluster: {
  name: TESTING,
  port: 6222,
  routes: [
    "nats://na_1:6222"
  ]
}
```

Docker compose for the cluster:

```yaml
version: "3.5"
services:
  na_1:
    image: nats
    command: -c /app/jetstream.conf --name na_1 -p 4222
    volumes:
      - ./testdata:/app
    ports:
      - 4222:4222
    networks: ["nats"]

  na_2:
    image: nats
    command: -c /app/jetstream.conf --name na_2 -p 4223
    volumes:
      - ./testdata:/app
    ports:
      - 4223:4223
    networks: ["nats"]

  na_3:
    image: nats
    command: -c /app/jetstream.conf --name na_3 -p 4224
    volumes:
      - ./testdata:/app
    ports:
      - 4224:4224
    networks: ["nats"]

networks:
  nats:
    name: nats
```
