### ISSUE TITLE
Config Parser does not consider variables in map keys

### ISSUE THREAD

**Issue by belowm** [nats-io/nats-server#6946]
### Observed behavior

This works:
```yaml
resolver_preload {
    "literal": $SOME_VALUE
}
```

This fails:
```yaml
resolver_preload {
    $SOME_KEY: "literal"
}
```

This fails with `unknown field "SOME_KEY"` (indicating the parser does not consider `$SOME_KEY` to be used, thus interpreting it as a field)

### Expected behavior

Variables should be valid at key position (my specific usecase: preload resolve with credentials from environment variable)

### Server and client version

v2.10.20

### Steps to reproduce

- create `issue.conf` file with below content
- run `nats-server -c issue.conf`

```yaml
SOME_SECRET: "<key>"

operator: "<jwt>"

resolver {
    type: full
    dir: /tmp
}

resolver_preload {
    $SOME_SECRET: "<jwt>"
}
```
